DE-2031: Fix silently ignoring invalid timezone
tetrascience/ts-task-script-utils pull request #1
Opened 2021-04-13 12:36 UTC by robjhornby-ts

Fixed bug that an invalid timezone like "EDT" (which isn't in the [tz timezone database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)) would silently fail and default to using UTC without raising an error.

Also:
- Simplified timezone parsing logic - we were repeating parts of what arrow.get already does (parsing timezone strings into datetime.tzinfo objects with error handling).
- Fixed bug in test cases - when asserting that errors were raised using try/catch, if the code didn't raise an error, the test would pass incorrectly. Now using pytest.raises to assert errors.
- Refactored tests to use pytest parametrize so that it's clearer which cases pass or fail (was useful for debugging)

2021-04-20 03:08 UTC, tlitetrasci requested changes
What's the difference between using `arrow` and `dateparser`? Why do we need both?

2021-04-20 03:08 UTC, tlitetrasci commented on task_script_utils/convert_datetime_to_ts_format.py
>      ts_datetime = (
Can simplify to:

```
return (datetime_iso_local
    .to()
    etc
)
```

No need to create extra variables

2021-04-20 03:08 UTC, tlitetrasci commented on __tests__/unit/test_convert_datetime_to_ts_format.py
> -    raw_expect = [
I like the conversion to parameterized tests.

I'm wondering how stringent we want this function to be. @wkopen What's using this at the moment? Personally I tend to have unique time parsing code for each instrument, since it constrains the problem.

Here are some example tests I wrote for the BMG date parser:
```


@pytest.mark.parametrize("tstamp, day_first", [
    # test swapping day/month order
    ("01.05.2020 07:57:30 (UTC+2)", True),
    ("01.05.2020 07:57:30 (UTC+2)", False),

    # test no time zone
    ("01.05.2020 07:57:30", True),

    # test using dashes as date separators
    ("03-09-2018 17:18:48", True),

    # test AM/PM parsing
    ("8/24/2020 5:53:52 PM (UTC+2)", False),
    ("8/24/2020 5:53:52 pm", False),

    ("4/30/2020 11:40:46 AM (UTC+2)", False),
    ("4/30/2020 11:40:46 am (UTC+2)", False),

    # test no leading zeroes for month
    ("1.5.2020 07:57:30", True),
    ("01.5.2020 07:57:30", True),

    # test no leading zeroes for day
    ("1.5.2020 07:05:30", False),
    ("1.05.2020 07:05:30", False),
])
def test_parse_good_timestamps(snapshot, tstamp: str, day_first: bool):
    res = parse_timestamp(tstamp, day_first)

    snapshot.assert_match(res)


@pytest.mark.parametrize("tstamp, day_first", [
    # test bad month
    ("8/24/2020 5:53:52 PM (UTC+2)", True),

    # test more than 24 hours
    ("4/30/2020 25:40:46 (UTC+2)", False),

    # test mixing separators
    ("8.24/2020 5:53:52 PM (UTC+2)", False),

    # test missing hour separator
    ("8/24/2020 553:52 PM (UTC+2)", False),

    # test time zone formatting
    ("8/24/2020 5:53:52 PM UTC+2)", False),
    ("8/24/2020 5:53:52 PM UTC+2", False),

    # test minutes not using leading zero
    ("8/24/2020 5:2:52 PM (UTC+2)", False),

    # test seconds not using leading zero
    ("8/24/2020 5:02:2 PM (UTC+2)", False),

    # test weird AM/PM formatting
    ("8/24/2020 5:53:52 pM (UTC+2)", False),
    ("8/24/2020 5:53:52 Am (UTC+2)", False),
])
def test_parse_bad_timestamps(tstamp: str, day_first: bool):
    with pytest.raises(Exception):
        res = parse_timestamp(tstamp, day_first)

```

The tests are really trying to probe the boundaries of what we expect to see in the raw files. Since this is such a general time parsing function, I wonder what the boundaries of this function are.

2021-04-21 13:57 UTC, robjhornby-ts commented
> What's the difference between using `arrow` and `dateparser`? Why do we need both?

I suspect the reason dateparser was used is because it handles non-ISO datetime strings by guessing the datetime format, which arrow doesn't do.

For example:

```
print(dateparser.parse("2020-04-30T10:27:41.000 EDT"))
```
output: `2020-04-30 10:27:41-04:00`

```
print(arrow.get("2020-04-30T10:27:41.000 EDT"))
```
raises `ParserError: Expected an ISO 8601-like string, but was given '2020-04-30T10:27:41.000 EDT'. Try passing in a format string to resolve this.`


I would be in favour of removing `dateparser` because we generally shouldn't trust the automatic format parsing with all the possible ambiguities it introduces (e.g. day-first-date format - `dateparser` has no way of knowing which to use). We know enough about the input files that we should always be able to determine the datetime format, which removes this potential source of bugs. On the other hand, several of the pipelines currently using this function rely on the `dateparser` path of the logic so this would not be a backward-compatible change. @wkopen what do you think?

2021-04-21 14:02 UTC, robjhornby-ts commented on task_script_utils/convert_datetime_to_ts_format.py
>      if datetime_format:
This function currently relies on the library functions it calls to raise any errors, so it's just acting as a wrapper to those functions. I agree it could be better to validate the inputs to this this function so we have more control over how it's used - it seems like there are design questions which need answering which are bigger than this bugfix.

2021-04-21 14:04 UTC, robjhornby-ts commented on task_script_utils/convert_datetime_to_ts_format.py
>          )
That's how I interpreted it but actually I think we should limit it to one datetime format and enforce that, I can't think of any use case for multiple formats - I'll make that change.

2021-04-21 14:05 UTC, robjhornby-ts commented on task_script_utils/convert_datetime_to_ts_format.py
> +        utc_indicator = ""
Agreed, I'll tidy that up

2021-04-21 14:06 UTC, robjhornby-ts commented on task_script_utils/convert_datetime_to_ts_format.py
> +        If timezone is not defined: "2019-07-17T11:21:00.000"
I'll make the examples more complete

2021-04-21 14:12 UTC, robjhornby-ts commented on task_script_utils/convert_datetime_to_ts_format.py
>          datetime_iso_local.to("GMT")
Changed

2021-04-21 14:16 UTC, robjhornby-ts commented on task_script_utils/convert_datetime_to_ts_format.py
>      ts_datetime = (
Agreed

2021-04-23 15:23 UTC, robjhornby-ts commented on __tests__/unit/test_convert_datetime_to_ts_format.py
> -    raw_expect = [
> What's using this at the moment?

I searched `ts-lib-protocol-script` for `task_script_utils.convert_datetime_to_ts_format` to get an idea of which task scripts are using this version of the function (this might not catch all uses).
To summarize, here are the arguments currently being used with this function:

`datetime` only: 10
`datetime` and `datetime_format`: 1
`datetime` and `timezone`: 1
`datetime`, `datetime_format` and `timezone`: 0

So `datetime` only is the most common input - handled by `dateparser` since there's no format string given. 

> I wonder what the boundaries of this function are

It seems like there are two parts to the functionality:

1. Convert parsed datetimes to the TS standard string format
2. Parse datetime strings

As a minimum, I think we should always use a function which implements part 1. This is common to all parsers which deal with datetimes, and it provides a single source of truth for the format which goes into an IDS - e.g. if we ever needed to change how datetimes are represented, we would only need to change it it one place.

I think it also makes sense to have part 2 be in a common library - datetime parsing is a general problem so it makes sense to have a general function shared across all parsers. This means all testing, maintenance and bugfixes only have to happen in one place instead of spread out and repeated across all parsers - your tests are all general for datetime parsing rather than instrument-specific so could be added to this function's tests.

This function is currently implementing these two parts. Then there's the third part which can't go in a central place:

3. Instrument-specific datetime parsing

This should only be needed if the instrument is using an unconventional datetime output, which is likely to be rare. This part has to live in each separate task script and can still make use of central functions once the instrument-specific part is parsed, to give a consistent output.


Do you think we should decide on all of these points before this bugfix is merged? Any bigger change in how this function works could also indirectly solve this bug, and potentially other unfound bugs, so that could make sense. @wkopen what do you think?

2021-04-26 00:43 UTC, wkopen commented
> > What's the difference between using `arrow` and `dateparser`? Why do we need both?
> 
> I suspect the reason dateparser was used is because it handles non-ISO datetime strings by guessing the datetime format, which arrow doesn't do.
> 
> For example:
> 
> ```
> dateparser.parse("2020-04-30T10:27:41.000 EDT")
> ```
> 
> output: `datetime.datetime(2020, 4, 30, 10, 27, 41, tzinfo=<StaticTzInfo 'EDT'>)`
> 
> ```
> arrow.get("2020-04-30T10:27:41.000 EDT")
> ```
> 
> raises `ParserError: Expected an ISO 8601-like string, but was given '2020-04-30T10:27:41.000 EDT'. Try passing in a format string to resolve this.`
> 
> I'm conceptually in favour of removing `dateparser` because we generally shouldn't trust the automatic format parsing with all the possible ambiguities it introduces (e.g. day-first-date format - `dateparser` has no way of knowing which to use). We know enough about the input files that we should always be able to determine the datetime format, which removes this potential source of bugs. On the other hand, several of the pipelines currently using this function rely on the `dateparser` path of the logic so this would not be a backward-compatible change. @wkopen what do you think?

I agree with this as we are moving towards a more precise data processing strategy (more permissive doesn't mean we will forgo quality). And using `dateparser` because it can try to guess the date and time is the opposite of what we want to do. If we make the change we need to bump the major version of this util library.

2021-04-26 01:23 UTC, wkopen requested changes
Looks good to me overall. Just some minor things. And I think the more general design discussion is out-of-scope of this ticket and shouldn't prevent it from merging. We can discuss that offline.

2021-04-26 01:23 UTC, wkopen commented on __tests__/unit/test_convert_datetime_to_ts_format.py
> -    raw_expect = [
I agree with Rob that we need a shared util code to handle time conversion. @tlitetrasci I'm curious why your test cases are specific to certain instruments. As Rob said, unless the instrument is using something unconventional, we should be able to define the date-time pattern for it and use this util function.

Toby, the test cases you provided above to test the boundary, to me it's more like testing the boundary of `arrow` or this util function, right?

And this topic shouldn't block this PR from merging because this PR fixes a bug in the existing function. If we need to further discuss it, we can start with a meeting. But it should not block this PR.

2021-04-26 01:23 UTC, wkopen commented on task_script_utils/convert_datetime_to_ts_format.py
> +            timezone database, e.g. "EDT" is not allowed, but is equivalent to
Is `EDT` really not allowed or it will not work if provided?

2021-04-26 01:23 UTC, wkopen commented on __tests__/unit/test_convert_datetime_to_ts_format.py
> +        ("2020-04-30T10:27:41.000", "America/New York", "2020-04-30T14:27:41.000Z"),
Can you add another one which is when US is in daylight saving so the difference with UTC+0 is actually 5 hours? Like 2020 Jan.1st

2021-09-03 15:20 UTC, closed without merging