DE-2999 refactor parse logic
tetrascience/ts-task-script-utils pull request #12
Opened 2022-02-11 12:35 UTC by setiat

2022-02-11 13:45 UTC, setiat commented
Logic changes for parse:

Right Now the signature of matcher functions looks like:
```python
def matcher_func(self, token:str) -> Dict[str, str]:
    # Logic goes here
```
The return type for each matcher is `Dict[str, str]`, where K,V pair  represent the name of the instance variable to be set  and its value.

The returned `dict` is used in `_parse` to actually [set the value](https://github.com/tetrascience/ts-task-script-utils/blob/DE-2999-refactor-parse-logic/task_script_utils/datetime_parser/datetime_info.py#L73).

Another way of doing this would be that each matcher function will set the value for instance variable and returns `True/False` depending on wether the value was matched or not. For example

```python
def _match_date(self, token:str) -> bool:
    # Logic goes here
    if day and month and year:
        self.day = day
        self.year = year
        self.month = month
        return True
    else:
        return False
```

The is better because this will explicitly set the instance variable. But each matcher will set the the values in its own scope. earlier it was centralised via `_parse`. 

@mlipschultz..Should I change the logic to use 2nd approach?

2022-02-11 20:22 UTC, mlipschultz reviewed
My concern with the current implementation (where it's centralized in `_parse`) is that it makes tracing through the code with tools (such as IDEs) difficult.  So I like the second approach more since it's easier to trace through the code and setting the values occurs where they're found.

Additional changes requested:
* All of these types will fail a type checker because their types are `str`, but their value is `None`: https://github.com/tetrascience/ts-task-script-utils/blob/master/task_script_utils/datetime_parser/datetime_info.py#L35
    * Perhaps `Optional[str]` would be better

I need to do some more review, but I wanted to save this before I lost it

2022-02-14 08:49 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +                        self.__dict__[key] = value
I have made the changes and every matcher sets the required variables. So these code lines are no longer required in parse.

I am not sure if I can get rid of _parse, even if it is removed...something is still required to iterate the tokens

2022-02-14 08:50 UTC, setiat commented
> My concern with the current implementation (where it's centralized in `_parse`) is that it makes tracing through the code with tools (such as IDEs) difficult. So I like the second approach more since it's easier to trace through the code and setting the values occurs where they're found.
> 
> Additional changes requested:
> 
> * All of these types will fail a type checker because their types are `str`, but their value is `None`: https://github.com/tetrascience/ts-task-script-utils/blob/master/task_script_utils/datetime_parser/datetime_info.py#L35
>   
>   * Perhaps `Optional[str]` would be better
> 
> I need to do some more review, but I wanted to save this before I lost it

- Added type hints in __init__
- Simplified _parse logic
- Updated matchers to set the instance variable and return True/False depending on wether a match was found or not

2022-02-15 12:53 UTC, mlipschultz requested changes
Additional comments:
* `long datetime_formats`: The [return type hint](https://github.com/tetrascience/ts-task-script-utils/blob/ebb9bfc14e2d940c20b75298160dd057862feeb9/task_script_utils/datetime_parser/datetime_info.py#L507) doesn't match the [type of your return value](https://github.com/tetrascience/ts-task-script-utils/blob/ebb9bfc14e2d940c20b75298160dd057862feeb9/task_script_utils/datetime_parser/datetime_info.py#L515).  `formats` is a generator.
* `_parse_with_formats`: Please add [a more specific exception](https://github.com/tetrascience/ts-task-script-utils/blob/ebb9bfc14e2d940c20b75298160dd057862feeb9/task_script_utils/datetime_parser/parser.py#L103)
* Please add type hints to the return values in https://github.com/tetrascience/ts-task-script-utils/blob/ebb9bfc14e2d940c20b75298160dd057862feeb9/task_script_utils/datetime_parser/ts_datetime.py#L10

2022-02-15 12:53 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
>      def _parse_long_date_formats(self):
The code path that goes through this method looks completely different than the code path through `_parse_short_date_formats`.  This one seems to set tokens to be used by [`_parse_with_formats`](https://github.com/tetrascience/ts-task-script-utils/blob/ebb9bfc14e2d940c20b75298160dd057862feeb9/task_script_utils/datetime_parser/parser.py#L78) whereas `_parse_short_date_formats` seems to set the actual extracted values from the string.  I feel like these two actions are different enough that they should be more separate.  The docstring for `DateTimeInfo` also points to this.  Most of the code in `DateTimeInfo` points to the class doing the parsing and storage of extracted datetime values (i.e. short date).  The long date work doesn't feel like it belongs since it's not doing any of that.  I'd suggest moving the long date code out of this class and move it closer to the pendulum parsing code.

2022-02-16 13:36 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
>      def _parse_long_date_formats(self):
Create a separate PR for this: #13

2022-03-03 15:08 UTC, mlipschultz commented
When doing some testing for a proposal (https://tetrascience.atlassian.net/wiki/spaces/DE/pages/3168239653?focusedCommentId=3183673359#comment-3183673359), I discovered a bug:
```python
>>> from task_script_utils.datetime_parser import parse
>>> parse('01/01/0001', ['MM/DD/YYYY']).tsformat()
'1-01-01T00:00:00'
```

The result should be `'0001-01-01T00:00:00'`.  Could you fix this as part of this PR?

2022-03-04 12:10 UTC, setiat commented
> ```python
> parse('01/01/0001', ['MM/DD/YYYY']).tsformat()
> ```

Fixed it as a part of #13 

I tried fixing this using python datetime  formatting tokens... But [build](https://app.travis-ci.com/github/tetrascience/ts-task-script-utils/builds/247405109) was failing even though tests were passing locally.

So I added custom function _pad_year to fix this

2022-03-07 09:55 UTC, setiat commented on task_script_utils/convert_datetime_to_ts_format.py
> +import dateparser, arrow
fixed

2022-03-07 09:55 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +        except ValueError as e:
fixed

2022-03-07 09:55 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +        except re.error as e:
fixed

2022-03-07 09:56 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +                raise OffsetNotKnownError(
fixed

2022-03-07 09:56 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        The format is YYYY-MM-DD hh:mm:ss and fractional seconds (upto 6 digit), AM/PM
fixed

2022-03-07 09:56 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +                # microseconds, therefore truncating fraction seconds to 6 digits
fixed

2022-03-07 09:57 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            raise InvalidDateError(f"{self.date_time_raw}")
fixed

2022-03-07 09:57 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    except DatetimeParserError as e:
fixed

2022-03-07 09:57 UTC, setiat commented on __tests__/unit/test_ts_datetime.py
> +    ts_datetime = from_pendulum_format(input_, format_, None, None)
fixed

2022-03-07 09:57 UTC, setiat commented on __tests__/unit/test_short_datetime_info.py
> +        d = ShortDateTimeInfo(input_, year_first)
fixed

2022-03-07 09:58 UTC, setiat commented on __tests__/unit/test_short_datetime_info.py
> +def _build_date_str_from_datetime_info(dt_info: ShortDateTimeInfo) -> str:
fixed

2022-03-07 09:58 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    except DatetimeParserError as e:
fixed

2022-03-07 09:58 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    except DatetimeParserError as e:
fixed

2022-03-07 09:58 UTC, setiat commented on __tests__/unit/test_ts_datetime.py
> +    ts_datetime = from_pendulum_format(input_, format_, None, None)
fixed

2022-03-07 09:58 UTC, setiat commented on task_script_utils/convert_datetime_to_ts_format.py
> +import dateparser, arrow
fixed

2022-03-07 13:44 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        hh_mm_ss_pattern = r"\d{1,2}:\d{1,2}:\d{1,2}\.\d+|^\d{1,2}:\d{1,2}:\d{1,2}$|^\d{1,2}:\d{1,2}:\d{1,2}[+-]"
ignored with inline comment

2022-03-07 13:44 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    "Sunday, May 26th 2013 12:12:12.0001 AM Asia/Kolkata +05:30": "2013-05-26T00:12:12.0001+05:30",
ignored with inline comment

2022-03-07 13:44 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    "Sunday, May 26th 2013 12:12:12.0001 AM Asia/Kolkata IST": "2013-05-26T00:12:12.0001+05:30",
ignored with inline comment

2022-03-07 13:44 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    "Sunday, May 26th 2013 12:12:12.0001 AM Asia/Kolkata": "2013-05-26T00:12:12.0001+05:30",
ignored with inline comment

2022-03-07 13:46 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    "Sunday, May 26th 2013 12:12:12.0001 AM Asia/Kolkata": "2013-05-26T00:12:12.0001+05:30",
ignored with inline comment

2022-03-07 13:46 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    "Sunday, May 26th 2013 12:12:12.5677 AM Asia/Kolkata": "2013-05-26T00:12:12.5677+05:30",
ignored with inline comment

2022-03-07 13:46 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    "Sunday, May 26 2013 12:12:12.0000 AM Asia/Kolkata": "2013-05-26T00:12:12.0000+05:30",
ignored with inline comment

2022-03-07 13:46 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    "Sunday, May 26 2013 12:12:12.5677 AM Asia/Kolkata": "2013-05-26T00:12:12.5677+05:30",
ignored with inline comment

2022-03-07 13:47 UTC, setiat commented on task_script_utils/datetime_parser/parser.py
> +        parsed_datetime, _ = parse_with_formats(datetime_str, config, formats_list)
max length changed to 88

2022-03-07 13:48 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            return time_format if time_format.startswith("H") else time_format + " A"
max length changed to 88

2022-03-07 13:48 UTC, setiat commented on __tests__/unit/test_short_datetime_info.py
> +    "input_, year_first, day_first, expected", two_digit_date_with_config_test_cases
max length changed to 88

2022-03-07 13:48 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +from task_script_utils.datetime_parser.parser_exceptions import DatetimeParserError
max length changed to 88

2022-03-07 13:48 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    "Sunday, May 26th 2013 12:12:12 AM IST Asia/Kolkata": "2013-05-26T00:12:12+05:30",
max length changed to 88

2022-03-07 13:48 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    "Sunday, May 26th 2013 12:12:12 AM Asia/Kolkata": "2013-05-26T00:12:12+05:30",
max length changed to 88

2022-03-07 13:49 UTC, setiat commented on __tests__/unit/test_long_datetime_info.py
> +    "Sunday, May 26th, 2013 12:12:12 AM Asia/Kolkata": "2013-05-26T00:12:12+05:30",
max length changed to 88

2022-03-07 13:49 UTC, setiat commented on __tests__/unit/test_datetime_parser_utils.py
> +    "Sunday, May 26th 2013 12:12:12 AM Asia/Kolkata": "2013-05-26T00:12:12+05:30",
max length changed to 88

2022-03-07 13:49 UTC, setiat commented on __tests__/unit/test_datetime_parser_utils.py
> +    parsed_datetime, _ = parse_with_formats(input_, DatetimeConfig(), formats_list)
max length changed to 88

2022-03-07 13:49 UTC, setiat commented on __tests__/unit/test_ts_datetime.py
> +    "input_, format_, expected_ts_format, expected_iso_format", padding_test_cases
max length changed to 88

2022-03-07 13:49 UTC, setiat commented on __tests__/unit/test_ts_datetime.py
> +def test_datetime_padding(input_, format_, expected_ts_format, expected_iso_format):
max length changed to 88

2022-03-07 13:53 UTC, setiat commented on __tests__/unit/test_short_datetime_info.py
> +def test_regex_parsing(input_, expected):
ignored

2022-03-07 14:14 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        hh_mm_ss_pattern = r"\d{1,2}:\d{1,2}:\d{1,2}\.\d+|^\d{1,2}:\d{1,2}:\d{1,2}$|^\d{1,2}:\d{1,2}:\d{1,2}[+-]"
max length changed to 88

2022-03-07 14:18 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +def parse_with_formats(
added doc strings

2022-03-07 14:23 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        for i, current_char in enumerate(char_list[1:-1]):
fixed

2022-03-07 14:23 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +    def _remove_T_between_two_digits(self, string: str):
fixed

2022-03-07 14:24 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +        Tuple[Optional[TSDatetime], Optional[str]]: return TSDatetime, matched_format
max Len changed to 88

2022-03-07 14:25 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +from .parser_exceptions import (
fixed

2022-03-07 14:25 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +from .parser_exceptions import (
fixed

2022-03-07 14:50 UTC, mlipschultz commented on __tests__/unit/test_datetime_parser_utils.py
> +import pytest
@abclay, what's the proper solution here?  Tarik disabled the error, but I don't know if it's the best approach.  I'm also not sure why reviewdog gave this error.

2022-03-07 16:50 UTC, abclay commented
I just want to point out that fixing/resolving all the pylint/flake8 errors is not necessary to merge the PR.  They are there more for information than for blocking.  I know it's overly verbose right now, so I apologize for that.  If you have feedback, I would recommend adding it to this doc or its comments:  https://tetrascience.atlassian.net/wiki/spaces/DE/pages/3164700810/Linting+Ignore+List+Proposals

2022-03-09 22:24 UTC, mlipschultz reviewed
I mostly have small requests.  I wasn't able to finish my review before ending for the day, but there's just one last thing I was hoping to look at.  Maybe someone else can review that part?

2022-03-09 22:24 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
>      def _parse(self, matchers):
I haven't had time to dig into whether this pattern still makes sense for the new parsing strategy (with two classes).  I think that's the only thing left for me to look at.  Unfortunately, I won't be able to review until Tuesday so maybe someone else can do that part of the review.

2022-03-10 13:26 UTC, abclay commented on .pylintrc
> +[MASTER]
Yes, this looks fine to me.

2022-03-17 12:12 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
>      def _parse(self, matchers):
I had a chance to look through this.  I don't like that the ShortDateTimeInfo matchers extract actual values while the LongDateTimeInfo matchers identify what token to use.  However, the outcome from the caller's perspective is the same, so I think I'm ok with it.

2022-03-21 11:25 UTC, setiat commented on task_script_utils/convert_datetime_to_ts_format.py
> +        except Exception:
I dont think `gettz` will ever raise except.. I tried passing gibberish to it and it returned None.

Can I create a separate ticket on fixing the old code? At this moment can't say how  changing code will impact behaviour in prod.

2022-03-21 11:25 UTC, setiat commented on task_script_utils/convert_datetime_to_ts_format.py
>              print(
Are print statements logged by platform?

2022-03-21 11:26 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +    def _pad_and_validate_offset_value(offset):
renamed the functions to :`_pad_and_validate_time_offset_value `

2022-03-21 11:35 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +    def _process_day_and_month(tokens: List[str]) -> tuple:
Fixed the name and function signature. It know access `first_token` and `second_token` instead of a list

2022-03-21 11:35 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            _ = dt(day=int(day), month=int(month), year=int(year))
fixed

2022-03-21 11:36 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            _ = dt(day=int(day), month=int(month), year=int(year))
fixed

2022-03-21 11:40 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +from typing import List, Optional, Tuple
fixed

2022-03-21 11:40 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            raise AmbiguousDateError(f"Can't decide day and month between: {first_token}, {second_token}")
fixed using black

2022-03-21 11:40 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            raise AmbiguousDateError(f"Can't decide day and month between: {first_token}, {second_token}")
fixed

2022-03-21 11:41 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            (first_token, second_token) if second_token_is_month else (second_token, first_token)
fixed

2022-03-21 11:41 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            raise AmbiguousDateError(f"Can't decide day and month between: {first_token}, {second_token}")
fixed

2022-03-21 11:41 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            raise AmbiguousDateError(f"Can't decide day and month between: {first_token}, {second_token}")
fixed

2022-03-21 11:41 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            (first_token, second_token) if second_token_is_month else (second_token, first_token)
fixed

2022-03-21 11:41 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +from typing import List, Optional, Tuple
fixed

2022-03-21 12:12 UTC, robjhornby-ts commented on task_script_utils/convert_datetime_to_ts_format.py
>              print(
I think this file has only changed because of pylint problems, is that right? I agree it would be nice to remove `print` from this function and use something more flexible, but I don't know what that would look like yet so maybe we could leave it for a future ticket.

It would be good to have a general way of logging / returning status messages which can easily be displayed as logs in the platform OR can easily be ignored by the caller, depending on what's wanted for that specific task script.

Would you rather replace it or remove it as part of this PR @mlipschultz ?

2022-03-21 12:56 UTC, mlipschultz reviewed
I have just two small docstring typos to fix.  Once the `print` statement is switched, I can approve

2022-03-21 13:14 UTC, mlipschultz commented on task_script_utils/convert_datetime_to_ts_format.py
> +        except Exception:
I forgot to mention that I'm not opposed to having this be a separate ticket, but I don't think I'd want to release until we decide about what to do when `None` is returned on bad input.

2022-03-21 13:28 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        """Takes two tokens as input and try to
fixed

2022-03-21 13:28 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            AmbiguousDateError: When it fail to decide between day and month
fixed

2022-03-21 13:30 UTC, setiat commented on task_script_utils/convert_datetime_to_ts_format.py
>              print(
added `warnings.warn` instead of `print`

2022-03-22 15:37 UTC, mlipschultz reviewed
Everything looks good.  There's still the question on what to do with non-timezone strings, but I'd like to get the perspective of @robjhornby-ts or @wkopen since they have more context.

2022-03-22 15:37 UTC, mlipschultz commented on task_script_utils/convert_datetime_to_ts_format.py
> +        except Exception:
When `None` is returned, there's [code later](https://github.com/tetrascience/ts-task-script-utils/blob/d841e2cdac3412743f27036ed9c4b4bffdaa5d9e/task_script_utils/convert_datetime_to_ts_format.py#L66) to handle a false-y value -- it'll default to GMT.  However, is this the behavior we want on unrecognized timezones?  This feels a little like hiding an error in the input, which could be a data integrity issue ([something we're trying to address right now elsewhere in our codebase](https://tetrascience.slack.com/archives/GMTG3FDNH/p1647259200879819)).  @robjhornby-ts, @wkopen, what are your thoughts here?

To summarize: If `tz.gettz` receives a string that can't be recognized as a timezone, it returns `None`.  Later in the code, if the `timezone_to_use` is false-y, we convert it to GMT without logging a warning/error (and without stopping parsing and raising an exception).  Is this behavior ok?  My guess is no, but I'd like confirmation

2022-03-22 15:37 UTC, mlipschultz commented on task_script_utils/convert_datetime_to_ts_format.py
> +        except Exception:
Also, @setiat, I tihnk we talked about converting this `Exception` to `AttributeError` because that's the only exception we know should occur (when a non-string is passed in).

2022-03-23 09:03 UTC, setiat commented on task_script_utils/convert_datetime_to_ts_format.py
> +        except Exception:
@mlipschultz and @robjhornby-ts 

`timezone` passed to `convert_datetime_to_ts_format` could be a `str`(valid or invalid) or it could be a `tz.offset`.  In case it is `tz.offset`, a `TypeError` is raised and code still works

If I pass an `int` as `timezone` and catch only `AttributeError`, code will still fail.

So, I have made following changes
- Updated typehints for `str` to `Union[tz.offset, str]`
- Handle only `TypeError`, every other exception will be raised
- added a test case

2022-03-23 10:55 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        except ValueError as e:
fixed.

2022-03-23 10:55 UTC, setiat commented on task_script_utils/convert_datetime_to_ts_format.py
> +        except AttributeError:
fixed

2022-03-23 10:55 UTC, setiat commented on __tests__/unit/test_convert_datetime_to_ts_format.py
> +from cmath import exp
fixed.

2022-03-23 10:55 UTC, setiat commented on __tests__/unit/test_convert_datetime_to_ts_format.py
> +        if type(expect) is str:
fixed

2022-03-23 13:04 UTC, mlipschultz reviewed
Thanks for switching to `TypeError`!

2022-03-23 13:04 UTC, mlipschultz commented on .travis.yml
> +  - pip install pipenv==2022.1.8
What's the reason for this specific version?

2022-03-23 13:16 UTC, setiat commented on .travis.yml
> +  - pip install pipenv==2022.1.8
Travis was struggling to run `Pipenv install --dev`. This is the fix for that

2022-03-24 20:05 UTC, wkopen commented
> Everything looks good. There's still the question on what to do with non-timezone strings, but I'd like to get the perspective of @robjhornby-ts or @wkopen since they have more context.

I don't think we should assume it to be "GMT", if timezone info is not available, we don't put timezone in the parsed string. And we def don't want to by-default using "GMT" without logging anything.

2022-03-25 13:33 UTC, robjhornby-ts commented
> Everything looks good. There's still the question on what to do with non-timezone strings, but I'd like to get the perspective of @robjhornby-ts or @wkopen since they have more context.

> When None is returned, there's [code later](https://github.com/tetrascience/ts-task-script-utils/blob/d841e2cdac3412743f27036ed9c4b4bffdaa5d9e/task_script_utils/convert_datetime_to_ts_format.py#L66) to handle a false-y value -- it'll default to GMT. However, is this the behavior we want on unrecognized timezones? This feels a little like hiding an error in the input, which could be a data integrity issue ([something we're trying to address right now elsewhere in our codebase](https://tetrascience.slack.com/archives/GMTG3FDNH/p1647259200879819)). @robjhornby-ts, @wkopen, what are your thoughts here?
> 
> To summarize: If tz.gettz receives a string that can't be recognized as a timezone, it returns None. Later in the code, if the timezone_to_use is false-y, we convert it to GMT without logging a warning/error (and without stopping parsing and raising an exception). Is this behavior ok? My guess is no, but I'd like confirmation

The default to GMT logic is a bit misleading, that branch of logic will lead to a datetime output with no timezone (`utc_indicator = ""`). It's a workaround because `arrow` and `dateparser` didn't have the functionality we needed.

The `convert_datetime_to_ts_format` function should be deprecated now that the new TS datetime parse function is ready to go. Or we should change `convert_datetime_to_ts_format` to use the new TS datetime parse function instead. Right now `convert_datetime_to_ts_format` has several problems which is why we wanted the new TS datetime library.

2022-03-25 13:45 UTC, mlipschultz commented
> The default to GMT logic is a bit misleading, that branch of logic will lead to a datetime output with no timezone (`utc_indicator = ""`). It's a workaround because `arrow` and `dateparser` didn't have the functionality we needed.

Thanks for the context.  If we keep the code, I think we should leave a comment so others understand in the future.  That said, ...

> The `convert_datetime_to_ts_format` function should be deprecated now that the new TS datetime parse function is ready to go. Or we should change `convert_datetime_to_ts_format` to use the new TS datetime parse function instead. Right now `convert_datetime_to_ts_format` has several problems which is why we wanted the new TS datetime library.

I think we should change the implementation to use the new TS datetime parser function -- no point in duplicating code.

2022-03-31 15:02 UTC, setiat commented
> > The default to GMT logic is a bit misleading, that branch of logic will lead to a datetime output with no timezone (`utc_indicator = ""`). It's a workaround because `arrow` and `dateparser` didn't have the functionality we needed.
> 
> Thanks for the context. If we keep the code, I think we should leave a comment so others understand in the future. That said, ...
> 
> > The `convert_datetime_to_ts_format` function should be deprecated now that the new TS datetime parse function is ready to go. Or we should change `convert_datetime_to_ts_format` to use the new TS datetime parse function instead. Right now `convert_datetime_to_ts_format` has several problems which is why we wanted the new TS datetime library.
> 
> I think we should change the implementation to use the new TS datetime parser function -- no point in duplicating code.

I have created a separate ticket for this effort --> https://tetrascience.atlassian.net/browse/DE-3634

2022-03-31 15:29 UTC, mlipschultz approved these changes
Thanks!

2022-04-01 06:32 UTC, merged