DE-2999 separate long and short date parsing
tetrascience/ts-task-script-utils pull request #13
Opened 2022-02-16 13:24 UTC by setiat

2022-02-17 12:39 UTC, mlipschultz requested changes

2022-02-17 12:39 UTC, mlipschultz commented on task_script_utils/datetime_parser/long_datetime_utils.py
> +    time_formats = [":".join(tokens) for tokens in product(*TIME_PARTS)]
Will there always be seconds in a long date format?

2022-02-17 12:39 UTC, mlipschultz commented on task_script_utils/datetime_parser/long_datetime_utils.py
> +        lambda x: [x, x + " Z", x + " z", x + " ZZ", x + " Z z", x + " ZZ z"],
Any reason `" zz"`, `" Z zz"`, and `" ZZ zz"` aren't included?

2022-02-17 12:39 UTC, mlipschultz commented on task_script_utils/datetime_parser/utils.py
> +from sqlite3 import Date
Some of these imports are unused

2022-02-17 12:39 UTC, mlipschultz commented on task_script_utils/datetime_parser/parser.py
> +        datetime_info._parse_long_date_formats()
You're accessing a protected method outside of the class.  Moving all long date code out of DateTimeInfo would resolve this problem

2022-02-17 12:39 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> -        self._parse_long_date_formats()
I'm not seeing this method removed from DateTimeInfo.  I'd also like to see:
1. `_parse_long_date_formats` moved out of this class
2. `_get_matchers_list` updated to only have the `long_date_formats=False` matchers
3. `_match_day_of_week_token`, `_match_month_token`, and `_match_day_token` moved out of this class

I'm seeing `DateTimeInfo` being a class that parses a string and extracts the date and time information.  The long date code in this class isn't doing that.  It's just identifying what tokens to use for parsing and that parsing was being done outside of this class already.  I know I originally suggested moving all long date code out of the class, but I think what's more correct is to put all long date code in one place (either all in this class or all out of this class).  Because of how separate the flows are between short and long parsing, I think it makes sense to separate the parsing.  However, I can see an advantage to having the final object look similar.  Perhaps it's best to have:
1. a `DateTimeInfo` class that's just responsible for:
    1. holding date and time information (i.e. `am_or_pm`, `iana_tz`, ..., `fractional_seconds`)
    2. all of the `@property` methods currently in `DateTimeInfo`
2. a `ShortDateTimeInfo` class that inherits from `DateTimeInfo` that's responsible for:
    1. containing all the methods for parsing a string using the short date time methods and setting all the date and time variables from the parent class
3. a `LongDateTimeInfo` class that inherits from `DateTimeInfo` that's responsible for:
    1. containing all the methods for parsing a string using the long date time methods and setting all the date and time variables from the parent class

You'll still need code to determine whether it's a long or short datetime, but you already have that so it's just a matter of updating the code.

2022-02-18 12:39 UTC, setiat commented on task_script_utils/datetime_parser/long_datetime_utils.py
> +        lambda x: [x, x + " Z", x + " z", x + " ZZ", x + " Z z", x + " ZZ z"],
Again long datetime parser was written in the context of empower agent.
But I still forgot `x + " z ZZ",
I have added all of them

2022-02-18 12:39 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +from sqlite3 import Date
removed.

2022-02-18 12:39 UTC, setiat commented on task_script_utils/datetime_parser/parser.py
> +        datetime_info._parse_long_date_formats()
fixed.

2022-02-18 12:41 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> -        self._parse_long_date_formats()
@mlipschultz Made the required changes. 
Doc strings and flowchart are still pending. Will wait till new changes are approved.

2022-02-24 15:23 UTC, mlipschultz requested changes
Thanks for separating the logic into separate classes!

In [__tests__/integration/test_datetime_parser.py](https://github.com/tetrascience/ts-task-script-utils/pull/13/files#diff-896bdb7560d9b4a7b0ec65de321fd56633f238de5eb5a8f6b38b8a1b1062cc2a), lines 46 and 47 are duplicates of lines 39 and 40.

2022-02-25 12:33 UTC, mlipschultz commented on task_script_utils/datetime_parser/long_datetime_utils.py
> +    time_formats = [":".join(tokens) for tokens in product(*TIME_PARTS)]
But what about other agents or sources for dates?  I can see that there exists at least one source for long dates that includes seconds, but is that true for all sources?

2022-03-02 09:06 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +        formats_with_no_zz = formats
fixed

2022-03-02 09:06 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +        except Exception as e:
fixed.

Catch -> ValueError and re.error

2022-03-02 09:06 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +def parse_with_formats(datetime_str: str, datetime_config, formats: Sequence[str] = ()):
added.

2022-03-02 09:07 UTC, setiat commented on task_script_utils/datetime_parser/parser.py
>              datetime_str, datetime_config=config, formats=formats_list
No particular reason.
Is this a bad habit?

2022-03-02 09:10 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        1. Repace a character if it is sandwiched between two integer
Fixed docstring.
I would like to rename it to `"remove 'T' between two digits"` as we can not ignore the possibility of getting `11:12:23A2018-13-09`

Waiting for @robjhornby-ts 's view on this.

2022-03-02 09:12 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        This property along with `dtstamp` property can be used
fixed

2022-03-02 09:13 UTC, setiat commented on __tests__/integration/test_datetime_parser.py
> -    "input, expected", format_list_with_no_tz_dict_test_cases.items()
removed.

2022-03-02 09:16 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        """This setter is mainly used by LongDateTimeInfo
`datetime` is a property.  This is why I went for `datetime.setter`

2022-03-02 09:24 UTC, setiat commented on task_script_utils/datetime_parser/long_datetime_utils.py
> +    time_formats = [":".join(tokens) for tokens in product(*TIME_PARTS)]
Long Datetime parser was written from the perspective empower's date-time format.
We still can have other sources... But we also provide a list of possible formats as format list

I am ok with whatever is decided here. 

It will just double the number of formats in the resultant format_list

2022-03-02 18:17 UTC, mlipschultz commented on task_script_utils/datetime_parser/long_datetime_utils.py
> +    time_formats = [":".join(tokens) for tokens in product(*TIME_PARTS)]
Since this is a utility meant to be used across task scripts, I'd rather have a general-purpose solution.  @robjhornby-ts, what are your thoughts on this since you have a better understanding than me of task script needs

2022-03-02 18:48 UTC, mlipschultz commented on task_script_utils/datetime_parser/parser.py
>              datetime_str, datetime_config=config, formats=formats_list
I think it was ok, it just made me wonder if I was missing something -- was there some parameter that wasn't being specified?

2022-03-02 18:52 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +        1. Repace a character if it is sandwiched between two integer
Thanks!  Looks like you missed the 'l' in "Replace" and the 's' in "integers".

I'll reach out to Rob on slack for the question.

2022-03-02 21:11 UTC, robjhornby-ts commented on task_script_utils/datetime_parser/datetime_info.py
> +        1. Repace a character if it is sandwiched between two integer
I think it makes sense to have this just remove `T` for now. If we come across another case that needs it we can update it, that seems like a safe option.

It looks like there's currently only 1 preprocessing step. To me it would make more sense to:
- only store the `date_time_raw` string
- remove `date_time_processed`
- put the `T` removing logic into a tokenization function (maybe a "_tokenize_datetime_string" function) which can be used here instead of using `.split()`: https://github.com/tetrascience/ts-task-script-utils/blob/18fcc19af9590d6354690158ffda58952b9fb564/task_script_utils/datetime_parser/datetime_info.py#L44?

The reason is that this step of replacing a letter with a space feels like it's an intermediate part of something else, so storing this intermediate result `date_time_processed` might not be that useful for other parts of the code. Storing the raw string and having 1 function which can tokenize it into tokens which are ready to use with `matchers` feels nicely encapsulated. Then if we ever need to add other rules about how we tokenize a raw datetime string before it's passed to `matchers`, that can all happen in the `_tokenize_datetime_string` function

2022-03-02 21:16 UTC, robjhornby-ts commented on task_script_utils/datetime_parser/long_datetime_utils.py
> +    time_formats = [":".join(tokens) for tokens in product(*TIME_PARTS)]
I agree we'd ideally make it general-purpose but I also haven't seen many long datetime formats without `seconds` yet so I think it's ok to require seconds for the immediate cases. How easy would it be to make the range of long datetime formats configurable? (Probably not easy unless you'd already anticipated this...)

How many other long date formats are we not covering? Maybe it's not possible to cover them all without some custom work per-task-script (and we can work out how to make that custom work as easy as possible, e.g. some kind of helper function for creating a list of long date formats, then that list of formats can be input to the usual format-list parser)

2022-03-02 21:38 UTC, mlipschultz reviewed
Thanks, looks like almost all my concerns are addressed!  I reached out to Rob for some clarification on requirements.  I think my remaining requests are all minor things due to miscommunication.

2022-03-02 21:38 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +        """This setter is mainly used by LongDateTimeInfo
I was asking why use this setter method here: https://github.com/tetrascience/ts-task-script-utils/blob/18fcc19af9590d6354690158ffda58952b9fb564/task_script_utils/datetime_parser/datetime_info.py#L246
when you could directly set day, month, ... there instead.  Looking back, my comment wasn't very clear, sorry!

I think what I'd like to see is a change to the docsting.  It doesn't need to talk about `LongDateTimeInfo`.  Unfortunately, I can't think of what the docstring should say since it seems self-explanatory to me.  Maybe it's not necessary?

2022-03-03 12:45 UTC, mlipschultz commented on task_script_utils/datetime_parser/long_datetime_utils.py
> +    time_formats = [":".join(tokens) for tokens in product(*TIME_PARTS)]
Based on Rob's response, it sounds like:
1. For this PR, we keep what you have
2. We can create a ticket for the helper function that'll create long datetime formats

@robjhornby-ts, to answer your question about how many long date formats we aren't covering, I think we cover all other cases.  Tarik did a thorough job of creating every combination of possibilities: https://github.com/tetrascience/ts-task-script-utils/blob/18fcc19af9590d6354690158ffda58952b9fb564/task_script_utils/datetime_parser/datetime_info.py#L330

2022-03-03 12:47 UTC, mlipschultz commented
It looks like you missed this (and I forgot about it in my previous review):

> In [\_\_tests\_\_/integration/test_datetime_parser.py](https://github.com/tetrascience/ts-task-script-utils/pull/13/files#diff-896bdb7560d9b4a7b0ec65de321fd56633f238de5eb5a8f6b38b8a1b1062cc2a), lines 46 and 47 are duplicates of lines 39 and 40.

2022-03-04 10:47 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        1. Repace a character if it is sandwiched between two integer
- added `_tokenize_datetime_string ` and `_remove_T_between_two_digits`
- removed `date_time_processed ` and `_preprocess_Datetime_str`

2022-03-04 10:48 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        """This setter is mainly used by LongDateTimeInfo
Removed the docstrings for datetime.setter

2022-03-04 12:11 UTC, setiat commented
> It looks like you missed this (and I forgot about it in my previous review):
> 
> > In [__tests__/integration/test_datetime_parser.py](https://github.com/tetrascience/ts-task-script-utils/pull/13/files#diff-896bdb7560d9b4a7b0ec65de321fd56633f238de5eb5a8f6b38b8a1b1062cc2a), lines 46 and 47 are duplicates of lines 39 and 40.

Removed duplicate data

2022-03-04 14:22 UTC, mlipschultz reviewed
Just one minor typo to fix, then it's ready to merge!

2022-03-04 14:22 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +        1. Repace the letter T if it is sandwiched between two digits
```suggestion
        1. Replace the letter T if it is sandwiched between two digits
```

2022-03-07 07:20 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        1. Repace the letter T if it is sandwiched between two digits
fixed.

2022-03-07 07:20 UTC, merged