WIP DE-3484 Update task script date time parser util to check for multiple format matches
tetrascience/ts-task-script-utils pull request #17
Opened 2022-03-14 22:39 UTC by apjansing

# DE-3484 Update task script date time parser util to check for multiple format matches

## Description 

Added `AmbiguousDatetimeFormatsError`  and `utils.does_format_list_contain_ambiguity` for checking for mutually ambiguous formats.

## Testing

Added `test_parse_with_ambiguous_formats_not_enforcing_unambiguity` and `test_parse_with_ambiguous_formats_enforcing_unambiguity` to `ts-task-script-utils/__tests__/integration/test_datetime_parser.py` to be run in `pipenv run python -m pytest`

2022-03-14 22:44 UTC, apjansing commented on task_script_utils/datetime_parser/utils.py
> +            except Exception as e:
I'm going to change this, and the existing instances of `except Exception`, to `DatetimeParserError`

2022-03-14 22:46 UTC, apjansing commented on __tests__/integration/test_datetime_parser.py
> +unambiguous_formats_list = [
I believe these come off as ambiguous and want to make sure that they would be if we enforce the unambiguous config for this

2022-03-16 20:59 UTC, abclay reviewed
I have a few comments and a suggestion for the ambiguity detector.

2022-03-16 20:59 UTC, abclay commented on __tests__/integration/test_datetime_parser.py
> +def test_parse_with_formats(input_: str, expected: Optional[str]):
Nice job adding all the type hints!

2022-03-16 20:59 UTC, abclay commented on __tests__/unit/test_check_for_mutual_ambiguity.py
> +    assert True
I don't think `assert True` does anything here.  It will never fail, so there's nothing to assert.

2022-03-16 20:59 UTC, abclay commented on pull_request_template.md
> +- [ ] PR Title should be in the form: "DE-12345: Short Description of Changes"
🏅

2022-03-16 20:59 UTC, abclay commented on task_script_utils/convert_datetime_to_ts_format.py
> +    datetime, datetime_format: Optional[str] = "", timezone: Optional[str] = ""
This argument name should probably be renamed to something else.  We would not be able to use the `datetime` library in this function, because the argument redefines in for the scope of the function.  Maybe call it something like `raw_datetime` ?

Alternatively, it looks like the `datetime` import is not used, so you could remove that to solve the issue as well.

2022-03-16 20:59 UTC, abclay commented on task_script_utils/datetime_parser/parser.py
> +        check_for_mutual_ambiguity(config.tz_dict, formats_list)
I read this as `check_for_moral_ambiguity` for a second and I was concerned.  🤔

2022-03-16 20:59 UTC, abclay commented on task_script_utils/datetime_parser/utils.py
> +def replace_abbreviated_tz_with_utc_offset(
I think this is a valid warning.  If you want to set a default, it should be `None`, then the code needs to check for that case:
```python
if tz_dict is None:
    tz_dict = {}
```

The type hint already is `Optional`, so I don't think it's a big deal.

2022-03-16 20:59 UTC, abclay commented on task_script_utils/datetime_parser/utils.py
> +def check_for_mutual_ambiguity(
Same as above.

2022-03-16 20:59 UTC, abclay commented on task_script_utils/datetime_parser/utils.py
> +                print(ambiguous_format_datetime, other_ambiguous_format_datetime)
Is this `print` supposed to be here?

2022-03-16 20:59 UTC, abclay commented on task_script_utils/datetime_parser/utils.py
> +        for other_datetime_format in formats_list - {datetime_format}:
These nested loops are going to check the same pairs of formats more than once.

For formats `[A,B]`, it will check both `A vs B` and `B vs A`, which should have the same result. In the end it's just checking to make sure all formats result in the same value.

This could be done in linear time:

```python
if not formats_list:
    # Make sure there's at least one format to compare
    return
formatted_date = do_the_format(formats_list[0])

for datetime_format in formats_list[1:]:
    cur_format = do_the_format()
    if cur_format != formatted_date:
        # you can either raise the error here, or gather up a list of errors to raise all at once after this loop.
```

Please correct me if I've misunderstood this function.

2022-03-17 16:14 UTC, apjansing commented on task_script_utils/datetime_parser/utils.py
> +def check_for_mutual_ambiguity(
So I had to split this function out into its own file because of a cyclic dependency. Since the `DatetimeConfig` uses something from `utils.py`, I couldn't use `DatetimeConfig` as a parameter type.
Now, `utils.py` is `utils/conversions.py` and this function is in its own file `utils/checks.py`. I also updated the references throughout the module.

2022-03-17 19:12 UTC, abclay reviewed
Just a couple last things from me, otherwise looks good.

2022-03-17 19:12 UTC, abclay commented on task_script_utils/datetime_parser/parser.py
> +    datetime_str: str, tz_dict: Optional[Dict] = [], formats: Sequence[str] = ()
`Optional[Dict]` is not compatible with the default `[]`

Also, we should avoid using `[]` and `{}` as defaults since they are mutable.  Here's a decent explanation: https://stackoverflow.com/q/1132941/6705467

2022-03-17 19:12 UTC, abclay commented on task_script_utils/datetime_parser/utils/conversions.py
> +    datetime_str: str, tz_dict: Optional[Mapping] = ()
Does `()` count as a `Mapping` ?

2022-03-17 21:34 UTC, apjansing commented on task_script_utils/datetime_parser/parser.py
> +    datetime_str: str, tz_dict: Optional[Dict] = [], formats: Sequence[str] = ()
I think I fixed this now. I changed a few of the function parameters to take the DatetimeConfig object now. I was only not doing this before because of the previously mentioned cyclic dependency but looks like it's not a problem anymore!

2022-03-17 21:34 UTC, apjansing commented on task_script_utils/datetime_parser/utils/conversions.py
> +    datetime_str: str, tz_dict: Optional[Mapping] = ()
Nope, but I fixed per the comment above https://github.com/tetrascience/ts-task-script-utils/pull/17#discussion_r829530970

2022-03-18 14:27 UTC, abclay approved these changes
:shipit:

2022-03-18 16:29 UTC, mlipschultz requested changes
I know I left a lot of comments, but they're mostly on the same thing (`Optional` type hint) -- sorry for all of them!

Great job with the implementation and thanks for cleaning up some broken windows :)

2022-03-18 16:29 UTC, mlipschultz commented on task_script_utils/datetime_parser/parser.py
> +    config: Optional[DatetimeConfig] = DEFAULT_DATETIME_CONFIG,
Probably another case where I don't think we want `Optional`

2022-03-18 16:29 UTC, mlipschultz commented on task_script_utils/datetime_parser/utils/conversions.py
> +def replace_zz_with_Z(formats: Optional[Sequence[str]] = ()):
What's the need for `Optional` and setting the default to an empty tuple?

2022-03-18 16:29 UTC, mlipschultz commented on task_script_utils/datetime_parser/utils/checks.py
> +    datetime_config: Optional[DatetimeConfig] = DatetimeConfig(),
Should this still be `Optional` (i.e. the value could be `None`) or is it just that there's a default value?

2022-03-18 16:29 UTC, mlipschultz commented on task_script_utils/datetime_parser/utils/checks.py
> +                pass
[FYI] You can catch multiple exceptions at once, e.g.:
```suggestion
            except (ValueError, AssertionError):
                # Ignoring ValueError, AssertionErrors because we're not concerned about validity of
                # parses in this function
                pass
```

2022-03-18 16:29 UTC, mlipschultz commented on task_script_utils/datetime_parser/utils/checks.py
> +        of possible datetime formats. Defaults to ().
```suggestion
        DEFAULT_DATETIME_CONFIG.
        formats_list (Optional[Sequence[str]], optional): List of possible datetime formats. Defaults to ().
```

2022-03-18 16:29 UTC, mlipschultz commented on task_script_utils/datetime_parser/utils/checks.py
> +        for other_datetime_format in formats_list[idx + 1 :]:
[FYI] You can use [itertools.combinations](https://docs.python.org/3/library/itertools.html#itertools.combinations) to simplify this a bit:
```suggestion
    for datetime_format, other_datetime_format in itertools.combinations(formats_list):
        input_ = ambiguous_datetime.format(datetime_format)
```
If you decide to implement this, you might want to have different names for the "datetime_format" variables, but it's not a big deal

2022-03-18 16:29 UTC, mlipschultz commented on task_script_utils/datetime_parser/utils/checks.py
> +                )
I think these can be moved out of the inner for-loop since they don't rely on `other_datetime_format`.

I know this recommendation is incompatible with my previous one on using `combinations`, so feel free to choose which you like more.

2022-03-21 11:05 UTC, setiat requested changes
@apjansing My apologies for a delayed review.
One of the change requested, is regarding the `check_for_mutual_ambigutity` functionality where it doesn't  take in account the raw datetime string. Please take a look and let me know if there are any questions.

2022-03-21 12:14 UTC, mlipschultz commented on task_script_utils/datetime_parser/utils/conversions.py
>      tz=None,
And I should have caught it :(

Should its type be `Optional[pendulum.tz.Timezone]` since its default is `None`?

2022-03-21 12:23 UTC, setiat commented on task_script_utils/datetime_parser/utils/conversions.py
>      tz=None,
Yes. :)

2022-03-21 18:20 UTC, apjansing commented on task_script_utils/datetime_parser/datetime_config.py
> +        enforce_unambiguity: Optional[bool] = False,
Yep! Reverting to just `bool` and updating the docstring

2022-03-21 18:21 UTC, apjansing commented on task_script_utils/datetime_parser/parser.py
> +    formats_list: Optional[Sequence[str]] = (),
Makes sense. Removed the optional

2022-03-21 18:23 UTC, apjansing commented on task_script_utils/datetime_parser/parser.py
> +    config: Optional[DatetimeConfig] = DEFAULT_DATETIME_CONFIG,
Yeah, this one I think was a carry-over from when I tried making it `None`, but then it made more sense to just use the `DEFAULT_DATETIME_CONFIG`. Updated

2022-03-21 18:25 UTC, apjansing commented on task_script_utils/datetime_parser/utils/conversions.py
> +def replace_zz_with_Z(formats: Optional[Sequence[str]] = ()):
Removed `Optional`

2022-03-21 18:27 UTC, apjansing commented on task_script_utils/datetime_parser/utils/conversions.py
>      tz=None,
Fixed!

2022-03-21 18:48 UTC, apjansing commented on task_script_utils/datetime_parser/utils/checks.py
> +                        to [{ambiguous_format_datetime}] and
Fixed

2022-03-21 18:48 UTC, apjansing commented on task_script_utils/datetime_parser/utils/checks.py
> +                        [{other_ambiguous_format_datetime}], respectively.
Fixed

2022-03-21 18:50 UTC, apjansing commented on task_script_utils/datetime_parser/utils/checks.py
> +                pass
Fixed! I figured that we could do this. I just didn't look it up :-X All I tried was `ValueError | AssertionError` because that's how you do it in Java, and then I figured I could move on by just having two `except` clauses

2022-03-21 18:52 UTC, apjansing commented on task_script_utils/datetime_parser/utils/checks.py
> +                    input_, other_datetime_format, tz=tz_dict
Why is it not `tz_dict`? I figured it would either be `None` or `{}` from `datetime_config`, or values we'd want

2022-03-21 18:55 UTC, apjansing commented on task_script_utils/datetime_parser/utils/checks.py
> +                    input_, other_datetime_format, tz=tz_dict
Oh... now that I'm looking at how pendulum.datetime works, it wouldn't make in a `dict`. Changing it to `None`

2022-03-21 18:59 UTC, apjansing commented on task_script_utils/datetime_parser/utils/checks.py
> +                    input_, datetime_format, tz=tz_dict
Changed

2022-03-21 19:11 UTC, apjansing commented on task_script_utils/datetime_parser/utils/checks.py
> +        for other_datetime_format in formats_list[idx + 1 :]:
Oh that is much better. I changed it to use `combinations`

2022-03-21 19:12 UTC, apjansing commented on task_script_utils/datetime_parser/utils/checks.py
> +                )
Using `combinations` :)

2022-03-21 19:16 UTC, apjansing commented on task_script_utils/datetime_parser/utils/checks.py
> +        of possible datetime formats. Defaults to ().
Fixed

2022-03-21 19:28 UTC, apjansing commented on task_script_utils/convert_datetime_to_ts_format.py
> +    datetime, datetime_format: Optional[str] = "", timezone: Optional[str] = ""
Removed!

2022-03-22 19:22 UTC, apjansing commented on task_script_utils/datetime_parser/utils/checks.py
> +def check_for_mutual_ambiguity(
So I understand where you're coming from with this but there was some discussion [on Confluence](https://tetrascience.atlassian.net/wiki/spaces/DE/pages/3168239653/Design+How+To+Incorporate+The+New+Date+Time+Parser+Into+Protocols) about this. After discussing this for a while with @yutaogui and @robjhornby-ts , re decided that `formats` (below) would raise and exception all the time when enforcement is active.
```
formats = [
     "MM/DD/YYYY HH:mm:ss",
     "DD/MM/YYYY HH:mm:ss"
]
```

2022-03-24 19:19 UTC, mlipschultz commented on task_script_utils/datetime_parser/parser.py
> +    formats_list: Sequence[str] = (),
We talked about renaming this to `formats`.  However, it looks like `formats_list` is starting to be used in task scripts:
- Here's a PR with it being used: https://github.com/tetrascience/ts-lib-protocol-script/pull/2453/files#diff-f3b2bc2938fa06706f5cb4878dfb58bb69fecb992596fda0af27e81a1b28d10bR253

I couldn't find any other uses in the dev branch of ts-lib-protocol-script, but they might be in the individual task script repos.

One option is to have both `formats_list` and `formats`.  If both have non-empty sequences, raise an exception.  Add a comment in the docstring that `formats_list` will be removed in a future release.

Another option is to just stick with `formats_list`.  I don't like this option, but it's probably best.  Unless we can convince Nils to hold off on merging until the `formats_list` -> `formats` change is merged.

2022-03-24 20:14 UTC, wkopen requested changes
Some documentation needs to be updated.

2022-03-24 20:14 UTC, wkopen commented on task_script_utils/datetime_parser/README.md
> +- `formats: Sequence[str] (optional)`: You can optionally pass a list of formats to try to parse datetime string. If `datetime_raw_str` doesn't matches with any format, the datetime parser will still
Now the behavior of the parser changes if there are multiple matches. Please add that new behavior here. The logic diagram also needs an update. Tarik has the original LucidChart, you can ask him to share the original file with you and save it on G Drive.

2022-03-25 23:08 UTC, apjansing commented on task_script_utils/datetime_parser/README.md
> +- `formats: Sequence[str] (optional)`: You can optionally pass a list of formats to try to parse datetime string. If `datetime_raw_str` doesn't matches with any format, the datetime parser will still
I updated the text around this and added more info on the config options.

I messaged @tariksetia about the LucidChart, but it was well past the end of his day on a Friday (2:22pm EST) 😄

2022-03-28 13:47 UTC, apjansing commented on task_script_utils/datetime_parser/README.md
> +- `formats: Sequence[str] (optional)`: You can optionally pass a list of formats to try to parse datetime string. If `datetime_raw_str` doesn't matches with any format, the datetime parser will still
Updated the parse-white.png LucidChart

2022-03-30 23:09 UTC, wkopen requested changes
Thanks for updating the diagram! There are some final touches on the README file I think is necessary. Please see my inline comments.

2022-03-30 23:09 UTC, wkopen commented on task_script_utils/datetime_parser/README.md
> +      - is `False`, the first valid parsed datetime valid will be returned.
Let's be consistent on the optional parameter documentation by adding `(optional)` after the parameter name.

2022-03-30 23:09 UTC, wkopen commented on task_script_utils/datetime_parser/README.md
> +v1.2.0
Empty line after this line. markdown linter will show a warning here.

2022-03-31 20:38 UTC, apjansing commented on task_script_utils/datetime_parser/README.md
> +v1.2.0
Added

2022-03-31 20:39 UTC, apjansing commented on task_script_utils/datetime_parser/README.md
> +- `formats: Sequence[str] (optional)`: You can optionally pass a list of formats to try to parse datetime string. If `datetime_raw_str` doesn't match with any format, the datetime parser will still t
Updated this and the `parse-white.png`! Take another look

about the `parse-white.png`... I couldn't figure out how to not have the one line cross over

2022-04-05 20:59 UTC, wkopen commented
Looks good! Some final touches then you are good. Don't forget to resolve merge conflicts.

2022-04-05 20:59 UTC, wkopen requested changes
Looks good! Some final touches then you are good. Don't forget to resolve merge conflicts.

2022-04-05 20:59 UTC, wkopen commented on task_script_utils/datetime_parser/README.md
> +    - `day_first (optional)`: Whether to interpret the first value in an ambiguous 3-integer date (e.g. 01/05/09) as the day (`True`) or month (`False`). Defaults to `None`.
because you already put the type into `()` for the top level params. Do you want to follow the same format for these nested params?

2022-04-05 20:59 UTC, wkopen commented on task_script_utils/datetime_parser/README.md
> +     - `True` and any of the formats produce a conflicting output, an `AmbiguousDatetimeFormatsError` will be raised.
`,` missing after `True`. Maybe `and` is not needed?

2022-04-05 20:59 UTC, wkopen commented on task_script_utils/datetime_parser/README.md
> +
markdown linter error. Multiple consecutive empty lines. `markdownlint` extension on VSCode will help you catch these and fix all of them for you.

2022-04-05 20:59 UTC, wkopen commented on task_script_utils/datetime_parser/README.md
> +```python
markdown linter - code block should be surrounded by empty lines

2022-04-07 19:13 UTC, apjansing commented on task_script_utils/datetime_parser/README.md
> +    - `day_first (optional)`: Whether to interpret the first value in an ambiguous 3-integer date (e.g. 01/05/09) as the day (`True`) or month (`False`). Defaults to `None`.
I think I fixed it to how you want it. I updated this and the datetime_config docstring that I ripped some of these descriptions from, using VSCode's docstring generator to make some more consistent type descriptions

2022-04-07 19:13 UTC, apjansing commented on task_script_utils/datetime_parser/README.md
> +
installed and fixed

2022-04-07 19:13 UTC, apjansing commented on task_script_utils/datetime_parser/README.md
> +     - `True` and any of the formats produce a conflicting output, an `AmbiguousDatetimeFormatsError` will be raised.
fixed!

2022-04-07 19:23 UTC, apjansing commented
@wkopen in the process of resolving the merge conflicts, I had to make some updates to the code. I had to move the `utils.py` to its own folder and break some of the code apart into separate files to fix a [cyclic dependency](https://www.sciencedirect.com/topics/computer-science/cyclic-dependency#:~:text=A%20cyclic%20dependency%20is%20formed,and%20Ordering%20Principle%20%5B80%5D.) between `parser.py`, `utils.py`, and `datetime_config.py` 

```mermaid
graph TD;
    datetime_config.py-->utils.py;
    parser.py-->utils.py;
    parser.py-->datetime_config.py;
    utils.py-->datetime_config.py;
```

2022-04-08 15:49 UTC, wkopen commented
I'm probably not suitable to review the refactor you did. Will need @tariksetia to review.

2022-04-12 14:24 UTC, setiat requested changes
Nice Work! Thanks for fixing cyclic dependency and enriching tests
I have requested a few changes as a parts of this review.

2022-04-12 14:31 UTC, setiat commented on task_script_utils/datetime_parser/utils/parsing.py
> +            except Exception:
This also applies to Line117
https://github.com/tetrascience/ts-task-script-utils/blob/bb116e27b9345c71444f4a6f89480d5845720f7d/task_script_utils/datetime_parser/utils/parsing.py#L117

2022-04-14 18:05 UTC, apjansing commented on __tests__/unit/test_check_for_mutual_ambiguity.py
> +import pytest
renamed!

2022-04-14 18:06 UTC, apjansing commented on __tests__/unit/test_check_for_mutual_ambiguity.py
> +    if datetime_config.require_unambiguous_formats:
I simplified the test, but I also pass the `datetime_config = DatetimeConfig(require_unambiguous_formats=True)` to the `parse_with_formats` function. Even if the formats aren't ambiguous, the config is there, so I figured we should use it.

```python
def test_require_unambiguous_formats_with_unambiguous_formats():
    datetime_str = "Saturday, February 3rd 2001 04:05:06 AM UTC"
    expected = "2001-02-03T04:05:06Z"
    datetime_config = DatetimeConfig(require_unambiguous_formats=True)
    result = parse_with_formats(
        datetime_str, formats=unambiguous_formats, config=datetime_config
    )
    assert expected == result.tsformat()
```

2022-04-14 18:10 UTC, apjansing commented on task_script_utils/datetime_parser/utils/parsing.py
> +            )
Added

2022-04-14 18:16 UTC, apjansing commented on task_script_utils/datetime_parser/utils/parsing.py
> +            except Exception:
Changed!

2022-04-14 18:16 UTC, apjansing commented on task_script_utils/datetime_parser/utils/parsing.py
> +):
Added!

2022-04-14 18:20 UTC, apjansing commented on task_script_utils/datetime_parser/utils/parsing.py
> +def _parse_with_formats(
Added

2022-04-14 19:16 UTC, apjansing commented on task_script_utils/datetime_parser/utils/parsing.py
> +                raise AmbiguousDatetimeFormatsError(
I added some logic to have an `updated_formats` list that starts out as a copy of the parameter passed to the function, then updated and used to parse the datetime function, but the originals are added to the list of tuples in the for-loop and later used in checking for multiple outputs:

```python
    updated_formats = copy(formats)
    if datetime_str_with_no_abbreviated_tz != datetime_str:
        # It means datetime_str did contain abbreviated_tz and we
        # have replaced it with its utc_offset value from tz_dict.
        # Now if the format in formats contains "zz", replace
        # it with "Z". This is because no library parses abbreviated tz
        # due to its ambiguous nature
        updated_formats = replace_zz_with_Z(updated_formats)

    if config.require_unambiguous_formats:
        parsed_times = []
        for idx, format_ in enumerate(updated_formats):
            try:
                parsed_times.append(
                    (
                        from_pendulum_format(
                            datetime_str_with_no_abbreviated_tz, format_, tz=None
                        ),
                        formats[idx],
                    )
                )
            except (ValueError, re_error):
                pass
           ...
           raise AmbiguousDatetimeFormatsError(
                    "Ambiguity found between datetime formats: "
                    f"{[parsed_time[1] for parsed_time in parsed_times]}, the parsed"
                    f" datetimes {list(unique_parsed_times.keys())}, and the input"
                    f" datetime string '{datetime_str}'."
                )
```

Ignore the formatting of the text. I added some linebreaks for readability here. The error message has not changed in the code.

Old
```
E                   task_script_utils.datetime_parser.parser_exceptions.AmbiguousDatetimeFormatsError: 
Ambiguity found between datetime formats: 
['MM/DD/YYYY hh:mm:ss A Z', 'DD/MM/YYYY hh:mm:ss A Z'], 
the parsed datetimes 
['2001-02-03T04:05:06+00:00', '2001-03-02T04:05:06+00:00'], 
and the input datetime string 
'02/03/2001 04:05:06 AM UTC'.
```

New
```
E                   task_script_utils.datetime_parser.parser_exceptions.AmbiguousDatetimeFormatsError: 
Ambiguity found between datetime formats: 
['MM/DD/YYYY hh:mm:ss A zz', 'DD/MM/YYYY hh:mm:ss A zz'], 
the parsed datetimes 
['2001-02-03T04:05:06+00:00', '2001-03-02T04:05:06+00:00'], 
and the input datetime string '02/03/2001 04:05:06 AM UTC'.
```

I've also added a unit test for this case in `test_check_for_mutual_ambiguity_in_formats_list.py`

2022-04-14 20:05 UTC, apjansing commented on task_script_utils/datetime_parser/utils/parsing.py
> +def parse_with_formats(
I changed a little about `parse_with_formats`. I moved
```
    # If the input datetime string contains Z to denote UTC+0,
    # then Z is replaced by +00:00
    datetime_str = replace_z_with_offset(datetime_str)
```
into the `_parse_with_formats` function that `parse_with_formats` calls. This cleans up the code a little, I think. The Pytests still pass when doing this. Also, I don't think any of the parser functions fail as soon as they find one conflicting format.

The way that I use `if len(Counter(unique_parsed_times).values()) > 1:` in `_parse_with_formats`, we parse against all possible formats (if we're requiring unambiguous formats), and then map-reduce them to something like this `Counter({'2001-02-03T04:05:06+00:00': 2, '2001-03-02T04:05:06+00:00': 1})` (this is hard to make happen without just putting the same format twice, but basically you'd end up getting `{k_1:1, k_2:1, ... k_n: 1}` for `n` different potential formats).

2022-04-18 08:57 UTC, setiat commented on task_script_utils/datetime_parser/utils/parsing.py
> +def _parse_with_formats(
the correct return type would be `Tuple[Optional[TSDatetime], Optional[str]]`

2022-04-18 09:02 UTC, setiat approved these changes
Approving this PR. Before merging,  Just a minor change is required for the return type of `_parse_with_formats`.

2022-04-18 09:02 UTC, setiat commented on task_script_utils/datetime_parser/utils/parsing.py
> +) -> Tuple[TSDatetime, str]:
The correct return type would be : `Tuple[Optional[TSDatetime], Optional[str]]`

2022-04-18 13:05 UTC, merged