DE-2591 datetime parser
tetrascience/ts-task-script-utils pull request #2
Opened 2021-10-11 13:23 UTC by setiat

2021-10-19 17:02 UTC, mlipschultz requested changes
I feel like I left a lot of comments, but overall it looks like you captured the flow we talked about and implemented the parsing rules.  Good job!

2021-10-20 15:09 UTC, setiat commented on Pipfile
> +ipykernel= "*"
This Pipfile was not updated. latest one has been pushed to repo
- ipykernel is moved to dev requirements, I use it as an alternative to python shell for quick experimenting
- dev packages also contain `autopep8`

2021-10-20 15:11 UTC, setiat commented on task_script_utils/datetime_parser/parser.py
> +        raise(e)
removed.

2021-10-20 15:22 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        date_tokens = [i for i in date.split("-")]
my bad! Fixed :)

2021-10-20 15:24 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            # 2 --> 02:00 | 09 --> +09:00 | 12 --> 12:00
fixed

2021-10-20 15:40 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            if self.am_or_pm and int(self.hour) <= 12:
In this case "2018-13-09T16:15+2 AM" will be parsed to "13-09-2018 16:15:00 +02:00"
As long as date_time string is not entered by a human manually, I don't this case will ever occur.
or if it occur, it will be like "13:00 PM", and this is not harmful
But if it not the case, parser should return None.

This raises one more point that I assumed.... If AM/PM is not detected , I am treating time_string  as military time//24hrs format.

2021-10-20 15:46 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +                # TODO: How to handle 01-15-11
cc @robjhornby-ts 
original Conversation : https://tetrascience.atlassian.net/browse/DE-2591?focusedCommentId=49636

2021-11-01 08:16 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +    def get_checks(self):
These are now protected methods

2021-11-01 08:17 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            t = token
removed

2021-11-01 08:18 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            self.day, self.month, self.year = day, month, year
fixed.
No matcher methods will alter instance variable.
It will just return the result

2021-11-01 08:18 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            return False, None
fixed

2021-11-01 08:19 UTC, setiat commented on task_script_utils/datetime_parser/parser.py
> +default_pipline_config = PipelineConfig(**{})
added `DEFAULT_PIPELINE_CONFIG` in `PipelineConfig.py`. Other modules will just import it.

2021-11-01 08:23 UTC, setiat commented on task_script_utils/datetime_parser/parser.py
> +    formats_list: list = None,
I changed it to `fomats_list: List[str] = []` 
Let me know if it works.

2021-11-01 08:30 UTC, setiat commented on task_script_utils/datetime_parser/parser.py
> +    dt_info.parse()
`DateTimeInfo.parse()` was just place holder. I was planning to add two more function: `parser_short_dates` and `parse_long_dates` and give `Parser.py` the power to decide which fx to call and when.

After implementing these methods, it make more sense to make them protected

2021-11-01 08:34 UTC, setiat commented on task_script_utils/datetime_parser/convert_to_iso_format.py
> +def convert_to_iso8601(
added return type and updated doc strings

2021-11-01 08:34 UTC, setiat commented on task_script_utils/datetime_parser/convert_to_iso_format.py
> +    formats_list: List[str] = None,
same as previous comment: `formats_list: List[str]=[]`

2021-11-01 08:55 UTC, setiat commented on task_script_utils/datetime_parser/parser.py
> +    dt_info.parse()
So now we have.
`_parse()`
`_parse_short_date_formats()`: called by `__init__`
`_parse_long_date_formats()`: called by `long_date_format`

2021-11-01 19:29 UTC, abclay reviewed
It would be useful to have a README file for the functionality offered by this library.  Especially for someone new like me, who has not been in any of the design decisions.

2021-11-01 19:29 UTC, abclay commented on task_script_utils/datetime_parser/datetime_info.py
> +        for i, current_char in enumerate(string[:-1]):
This function might be simpler if you:

1. Change the string to a list of characters: `chars = list(string)`
2. Loop through the list, changing whatever you need to change.  Not great example: `chars[5] = " "`
3. Create the final string: `return "".join(chars)`

You can also skip keeping track of prev, cur, and next characters by just starting from the 2nd element. Something like this: 

```python
char_list = list(string)
for i, char in enumerate(char_list[1:-1]):
    if (
        char_list[i-1].isdigit()
        and char_list[i].isalpha()
        and char_list[i+1].isdigit()
    ):
        char_list[i] = " "
return "".join(char_list)
```

2021-11-05 11:05 UTC, setiat commented on __tests__/unit/test_datetime_info.py
> +    ("1:2:32 20-11-1 -1 AM America/Chicago", "01-11-2020 1:2:32 AM -01:00 America/Chicago"),
These test cases were written only to check if regex parsing and validation works or not.
`convert_to_ts_iso_8601` takes care of the final formatting.

2021-11-08 12:20 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        for i, current_char in enumerate(string[:-1]):
fixed.

2021-11-08 12:20 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +                f"Invalid time : {time_}. Hours value is incorrect"
Done.

2021-11-08 12:20 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        date successfully, it will be stored in `self.short_date`
updated doc strings

2021-11-08 12:21 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        #    self.offset_ = pendulum.now(tz=self.iana_tz).format("Z")
removed.

2021-11-08 12:22 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        self._pre_process_datetime_string()
I agree. made the change

2021-11-08 12:23 UTC, setiat commented on task_script_utils/datetime_parser/convert_to_iso_format.py
> +    formats_list: List[str] = [],
it is now `formats_list: Tuple[str] = (), `

2021-11-08 12:24 UTC, setiat commented on __tests__/unit/test_datetime_parser.py
> +prase_with_no_format_list_test_cases = {
@abclay Please help,  I am not sure what changed here?

2021-11-08 12:59 UTC, setiat commented on __tests__/unit/test_datetime_parser.py
> +prase_with_no_format_list_test_cases = {
Thanks 🙈

2021-11-08 13:02 UTC, setiat commented on __tests__/unit/test_datetime_parser.py
> +prase_with_no_format_list_test_cases = {
fixed.

2021-11-08 13:02 UTC, setiat commented on __tests__/unit/test_datetime_parser.py
> +    prase_with_no_format_list_test_cases.items()
fixed

2021-11-09 13:48 UTC, abclay approved these changes
All my concerns have been addressed.  Nice work!

2021-11-09 14:18 UTC, mlipschultz requested changes
I really like the README!

2021-11-09 14:18 UTC, mlipschultz commented on README.md
> +|                            | SSSSSS   |                                         |
I'm confused by these two lines.
- The first shows four `S`es, but the output only shows three required digits (unless I'm misinterpreting the brackets).
- What does the ellipsis (`...`) mean after the `S`es?  That I can put more than four `S`es?
- The `SSSSSS` token doesn't have any example output.

2021-11-09 14:18 UTC, mlipschultz commented on __tests__/unit/test_convert_to_iso.py
> +    #TODO: Confirm these cases
Did you ever confirm these cases?

2021-11-09 14:18 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +            if self.am_or_pm and int(self.hour) <= 12:
I think it's safe to assume military time if AM/PM isn't detected.  I'm not sure if parsing 13:00 AM as 13:00 PM or 1:00 PM is safe though.  I'll defer to @robjhornby-ts's opinion here since he's more familiar with the problem.

2021-11-09 14:18 UTC, mlipschultz commented on task_script_utils/datetime_parser/parser_exceptions.py
> +class InvalidYearError(DatetimeParserError):
You're missing an empty line here.  I think there are supposed to be [two blank lines between classes](https://www.python.org/dev/peps/pep-0008/#blank-lines) though.

2021-11-10 09:33 UTC, setiat commented on task_script_utils/datetime_parser/parser_exceptions.py
> +class InvalidYearError(DatetimeParserError):
fixed

2021-11-10 09:35 UTC, setiat commented on __tests__/unit/test_convert_to_iso.py
> +    #TODO: Confirm these cases
Nope, I couldn't find much examples of how `fold` works.
Need to build more test cases. It works for examples in confluence doc

2021-11-10 09:38 UTC, setiat commented on README.md
> +|                            | SSSSSS   |                                         |
I couldn't find any documentation for `...` in pendulum docs/ test cases.
May be it is  their shorthand to say that it works for 4,5 and 6 fraction digits as well.
I have updated the doc. It works for at max 6 digits.

```python
>>> import pendulum as p
>>> a =p.now()
>>> a.format("SSSSSS")
'105620'
>>> a.format("SSSSS")
'10562'
>>> a.format("SSSS")
'1056'
>>> a.format("SSS")
'105'
>>> a.format("SS")
'10'
>>> a.format("S")
'1'
```

2021-11-10 09:38 UTC, setiat commented on README.md
> +| DayFirst(down)/ Year_first | True     | False                  | None                                 |
fixed

2021-11-10 09:39 UTC, setiat commented on __tests__/unit/test_datetime_parser.py
> +    #Error Case
added

2021-11-11 10:00 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +                # TODO: How to handle 01-15-11
The logic was updated as per test cases in google docs

2021-11-11 10:00 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        month = f"0{month}" if month < 10 else str(month)
fixed

2021-11-11 10:02 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        matches = re.findall(pattern, token)
fixed.

2021-11-11 10:11 UTC, setiat commented on task_script_utils/datetime_parser/date_formats.py
> +    ['Do,', 'Do', 'D,', 'D'],
The logic has changed.  The the date format is built by looking at the datetime string and trying to find out which formatting token should be used. `DatetimeInfo.long_date_format` return the date format. Then a Cartesian product with all possible time formats is done to build a list of possible datetime formats.

This reduces the formatting list to 192 from 6400

2021-11-11 10:14 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        hh_mm_pattern = r"\d{1,2}:\d{1,2}[+-]|\d{1,2}:\d{1,2}\s+|\d{1,2}:\d{1,2}$"
When the `seconds` are missing from time, `time` and offset will look the same. [+-] is used to distinguish between time and offset in this case.

2021-11-11 11:00 UTC, robjhornby-ts commented on task_script_utils/datetime_parser/datetime_info.py
> +            if self.am_or_pm and int(self.hour) <= 12:
I've never seen a case like this so I think we can form an opinion. It should be rare.

My opinion is
- `13:00 AM` should be ambiguous, something like "AM/PM doesn't match time of day"
- `13:00 PM` - I wouldn't be surprised if this is produced by some software, but I haven't seen it so I'm not sure. Really, the "PM" is correct, it's just using a 24 hour clock and giving superfluous extra information that 13:00 is after midday. I think we can accept it but it's a grey area.
- If there is no AM/PM, assume it's a 24 hour format

2021-11-23 15:24 UTC, mlipschultz requested changes

2021-11-23 15:24 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +    def _match_time(self, token: str) -> Union[str, None]:
You'll need to update this and other methods' type hints for the return type.

2021-11-24 07:30 UTC, setiat commented on task_script_utils/datetime_parser/convert_to_iso_format.py
> +    formats_list: Tuple[str] = (),
fixed.

2021-11-24 07:30 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +    def _match_time(self, token: str) -> Union[str, None]:
fixed.

2021-12-02 13:22 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +        hh_mm_ss_pattern = r"\d+:\d+:\d+.\d+|\d+:\d+:\d+"
Since it's been awhile, @setiat what are your plans for this comment?

2021-12-02 17:36 UTC, mlipschultz requested changes

2021-12-02 17:36 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +        """Returns YYYY-MM-DD"""
Not necessarily.  There are code paths that can result in single-digit months and days, meaning this method may also return `YYYY-M-D`.  Can you update the code so that this method (and others, where appropriate) always return date as `YYYY-MM-DD`?  Can you also add tests to confirm this behavior?

To confirm this, I added `("2021.11.7", None, False,'2021-11-07'),` to `two_digit_date_with_config_test_cases` in the `datetime_info.py` test file.  I was suspicious that `_process_year_first_or_last_matches` wasn't doing any padding to the days and months.

2021-12-02 17:36 UTC, mlipschultz commented on task_script_utils/datetime_parser/convert_to_iso_format.py
> +):
```suggestion
) -> str:
```

2021-12-02 17:36 UTC, mlipschultz commented on __tests__/unit/test_convert_to_iso.py
> +    #TODO: Confirm these cases
What do you need to confirm these?  @robjhornby-ts, would you be able to help out here?

2021-12-03 01:45 UTC, robjhornby-ts commented on __tests__/unit/test_convert_to_iso.py
> +    #TODO: Confirm these cases
Sorry for taking a while to get to this. These ones are correct. I'd add these which already work as expected with the current code:

```
    # On a date when the fold is irrelevant, it is ignored
    ("2021-11-06T01:30:00 America/New_York", 0, "2021-11-06T05:30:00.032Z"),
    ("2021-11-06T01:30:00 America/New_York", 1, "2021-11-06T05:30:00.032Z"),
    ("2021-11-08T01:30:00 America/New_York", 1, "2021-11-08T06:30:00.032Z"),
    ("2021-11-08T01:30:00 America/New_York", 0, "2021-11-08T06:30:00.032Z"),

    # Other timezones
    ("2021-10-31T01:15:00 Europe/London", 1, "2021-10-31T01:15:00Z"),
    ("2021-10-31T01:15:00 Europe/London", 0, "2021-10-31T00:15:00Z"),
    ("2021-10-31T02:45:00 Europe/Rome", 1, "2021-10-31T01:45:00Z"),
    ("2021-10-31T02:45:00 Europe/Rome", 0, "2021-10-31T00:45:00Z"),
```

We'll need to change the logic slightly for when `fold=None` - it should raise an error like AmbiguousFoldError if `fold=None` during a time when `fold` is required to disambiguate the datetime. These cases should raise an error. Each one is `(input_, fold)`

```
    # Raises AmbiguousFoldError
    ("2021-11-07T01:30:00 America/New_York", None),
    ("2021-11-07T01:20:00.03 America/New_York", None),
    ("2021-10-31T01:15:00.123 Europe/London", None),
    ("2021-10-31T02:45:00.0 Europe/Rome", None),
```

The reason these are ambiguous is because their UTC time could be one of two different values depending on whether fold = 0 or 1. A simple way to check using the existing code could be something like this, assuming a TSDatetime has already been created:

```python
import copy


def is_fold_required(datetime_: TSDatetime) -> bool:
    """Check whether an undefined `fold` would cause an ambiguous TSDatetime

    The "fold" is required during the 2 hour window when clocks are set back in
    a timezone which keeps track of daylight savings (such as IANA timezones
    like `Europe/London`).

    This function returns True if "fold" is required to disambiguate a
    datetime, False otherwise.
    """
    # Copy because TSDatetime is mutable
    dt = copy.deepcopy(datetime_)
    dt.change_fold(0)
    dt_before_fold = dt.ts_format
    dt.change_fold(1)
    dt_after_fold = dt.ts_format

    return dt_before_fold != dt_after_fold

if fold is None and is_fold_required(datetime_):
    raise AmbiguousFoldError(
        "This time is during the transition from daylight savings to standard "
        f"time: {datetime_input_string}. To disambiguate it, we need to know "
        "whether it is 'before the fold' (during daylight savings time) or "
        "'after the fold' (during standard time)."
    )
```

There might be a simpler way too (e.g. I'm not sure if I need to use `dt.ts_format` for the comparison, might be overkill)

2021-12-03 02:46 UTC, robjhornby-ts reviewed
A couple of comments

I think we found that some places in the world use a YYYY/DD/MM date format so we couldn't assume that `AAAA BB CC` is always Y M D. But it seems odd that `parse(datetime_str="2021-01-02T01:30:00Z")` requires a `day_first` `False` config, even though it follows the RFC3999 format and our own TS ISO format. It feels like the default behaviour should be that it accepts a format of `YYYY-MM-DDTHH:mm:ssZ` (with or without microseconds, optionally with a space instead of the `T`, and with any kind of supported timezone, not just the `Z` token) as unambiguous. 

Could we potentially do this by defining our default `formats_list` to contain some formats like above, instead of an empty tuple? Or maybe create a tuple of formats which can be passed to the formats_list input like `parse(datetime_str="2021-01-02T01:30:00Z", formats_list=DEFAULT_FORMATS)` (maybe with a better name)

If any of these comments would take a long time to implement, I'm also happy to leave them as future improvements instead of prolonging this PR

2021-12-03 02:46 UTC, robjhornby-ts commented on README.md
> +- `fold`: `0` or `1`
Might want to add an explanation too, hopefully this isn't too long but people seem to find "fold" confusing without giving all the detail.

Fold is relevant for timezones which refer to both a daylight savings time and a standard time, such as IANA timezones like `America/New_York` which is `-05:00` in standard time and `-04:00` in daylight savings time. For these timezones, there is a period around the transition from daylight savings to standard time where the same time appears on the clock twice, an hour apart. Without knowing whether it's the first time (fold=0) or the second time (fold=1), the datetime is ambiguous when converting to UTC.

For example, on the date when daylight savings end in New York, "2021-11-07T**01**:30:00 **America/New_York**" could refer to either "2021-11-07T**05**:30:00**Z**" or "2021-11-07T**06**:30:00**Z**" depending on the fold. Supplying a `fold` of `0` or `1` disambiguates this. However, `fold` is typically not provided with raw data using this format: if `fold` is required to convert to UTC reliably, but isn't included in the datetime config, an error will be raised. See [PEP 495](https://www.python.org/dev/peps/pep-0495/) more on disambiguating local time.

2021-12-06 07:19 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        hh_mm_ss_pattern = r"\d+:\d+:\d+.\d+|\d+:\d+:\d+"
updated the regex pattern, they are not exactly the same as suggested. But they cover the test cases

2021-12-06 07:24 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            Union[str, None]: return if any time string is found
fixed

2021-12-06 07:25 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        """Returns YYYY-MM-DD"""
Updated the doc string... The idea is to return raw values as year-month-day

2021-12-06 09:21 UTC, setiat commented on __tests__/unit/test_datetime_info.py
> +    except Exception as e:
fixed.

2021-12-06 09:21 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        two_digit_date_pattern = r"^\d{1,2}[-./\\]\d{1,2}[-./\\]\d{1,2}"
fixed

2021-12-06 18:56 UTC, mlipschultz commented on __tests__/unit/test_datetime_info.py
> +        result = date_info.date_str
@robjhornby-ts: Continuing the conversation [from another thread](https://github.com/tetrascience/ts-task-script-utils/pull/2#discussion_r762754313), if the input string is `"2021.11.7"`, is the correct output:
1. `'2021-11-07'`
2. `'2021-11-7'`
3. Both would be considered valid

2021-12-06 20:52 UTC, robjhornby-ts commented on __tests__/unit/test_datetime_info.py
> +        result = date_info.date_str
The only place I see this property used is in this test, not in the logic for creating the TS ISO 8601 string. Can we delete the `date_str` and `time_str` properties of the DateTimeInfo class and change these tests to use other properties of the DateTimeInfo object instead?

@tariksetia the DateTimeInfo class has a lot of methods and is relatively complex already, we could remove everything which isn't used elsewhere in the parsing logic.

2021-12-06 22:54 UTC, mlipschultz commented on __tests__/unit/test_datetime_info.py
> +        result = date_info.date_str
Good catch Rob!  I didn't realize `date_str` was only used in the tests.  I agree with removing the methods only used in testing.  I'd still like to keep the test cases around though, so Tarik can you update the tests for `convert_to_ts_iso8601` to also include these test cases?

2021-12-07 09:14 UTC, setiat commented on __tests__/unit/test_datetime_info.py
> +        result = date_info.date_str
`date_str` and `time_str` are required for internal processing when parsing date and time.

[line 71](https://github.com/tetrascience/ts-task-script-utils/blob/DE-2591-datetime-parser/task_script_utils/datetime_parser/datetime_info.py#L71) and [line 96](https://github.com/tetrascience/ts-task-script-utils/blob/DE-2591-datetime-parser/task_script_utils/datetime_parser/datetime_info.py#L97)

2021-12-07 09:27 UTC, setiat commented on __tests__/unit/test_datetime_info.py
> +        result = date_info.date_str
- `DateTimeInfo` is an internal data structure. Not to be used by developer. So wether it is '2021-11-07' or `'2021-11-7'`, should not matter at DateTimeInfo level
- Developer can use only `convert_to_ts_iso8601` and `parse`
-`convert_to_ts_iso8601` uses `parse()` internally
- Now `parse` returns `TSDatetime` which exposes
      - `TSDatetime.datetime`: return python datetime object
      -  `TSDatetime.iso_format`: return date time str with 2 digit months and days
      -  `TSDatetime.ts_format`: return date time str with 2 digit months and days

2021-12-07 19:37 UTC, mlipschultz commented on __tests__/unit/test_datetime_info.py
> +        result = date_info.date_str
> `date_str` and `time_str` are required for internal processing when parsing date and time.

The way the code's written, it's not possible for us to make use of the code tracing tools that IDEs like PyCharm and VS Code provide, making maintenance of the code difficult.  For example, finding usages of the `date_str` property doesn't find line 97 because that's just a string and the IDE doesn't know that `"date_str"` refers to the property `date_str`.  I'd like to see the code rewritten to enable this kind of tracing, but I think that's another issue.

> Developer can use only `convert_to_ts_iso8601` and `parse`

This is why I'm thinking we need to have more tests on these functions.  For example, there are no tests confirming that they always return 2-digit months and days.  The only tests at this level are for fold and fractional seconds.  It would be good to have some smoke tests just to confirm that everything works as expected.  I think the smoke tests should include:
* the cases in [the datetime_dayfirst_yearfirst spreadsheet](https://docs.google.com/spreadsheets/d/1GM_rbbYWab9h_NIs-WKLAdHvh-zJQqDpRgb0buk2EG0/edit#gid=0)
* are month and days always digits long?

I know you have tests for this already, but they're on methods that are known to not produce the correct output (e.g. `date_str` on single-digit months and days).  That's why I'm asking for smoke tests on the front-end functions developers are expected to use.  Having these tests on the front-end will also create a safety net if/when we update the backend to my concern above about maintainability.

2021-12-08 09:52 UTC, setiat commented on README.md
> +- `fold`: `0` or `1`
added

2021-12-08 10:44 UTC, setiat commented on __tests__/unit/test_datetime_info.py
> +        result = date_info.date_str
added tests for padding  and configured padding for date and time parts in logic.
If it is not urgent can I take parser modification as  a separate task for later sprints along?

2021-12-08 11:16 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +        """Returns YYYY-MM-DD"""
added padding to  all datetime parts

2021-12-08 21:47 UTC, mlipschultz reviewed
I talked with Kai and we realized it'd be better to have a single function as the entrypoint to the parsing.  We think it should be the `parse` function since you can use `parse(...).tsformat()` to get a TS-formatted string.  To accomplish this, can you:
1. Add a docstring to the `parse` function (the one for `convert_to_ts_iso8601` would work with some minor changes)
3. Rename `iso_format` to isoformat` and make it a method.  This is so it's consistent with [Python's datetime object method](https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat) -- reduces cognitive load on developers.
2. Rename `ts_format` to `tsformat` and make it a method.  This is to be consistent with `isoformat` above.

Eventually, we will remove `convert_to_ts_iso8601` but in the interest of time we'll leave it for now.  This also means that for now we can keep the tests on `convert_to_ts_iso8601` instead of moving them to `parse`.  I've also added this to the future issue.

2021-12-08 21:50 UTC, mlipschultz commented
@robjhornby-ts, @wkopen: Should we be able to parse just dates or just times, e.g.:
```python
parse('2021-12-08')
parse('12:49:51')
```
Or should those produce errors?

2021-12-09 06:14 UTC, wkopen commented
> @robjhornby-ts, @wkopen: Should we be able to parse just dates or just times, e.g.:
> 
> ```python
> parse('2021-12-08')
> parse('12:49:51')
> ```
> 
> Or should those produce errors?

Yes I think there are cases where only date or time is provided. It's not a common case though. Let's make a separate ticket for it and document in the README it's a limitation. Not required in this version.

2021-12-09 06:30 UTC, wkopen requested changes
I only reviewed the test cases. Will keep reviewing tomorrow.

2021-12-09 06:30 UTC, wkopen commented on __tests__/unit/test_datetime_parser.py
> +format_list_test_cases = {
is `formatted_list_test_cases` better? just `format` makes it sound like a verb. If you agree, then please update the others

2021-12-09 06:30 UTC, wkopen commented on task_script_utils/datetime_parser/datetime_config.py
> +        # The "fold" is required during the 2 hour window when clocks are set back in
This is good but I think docstring is a more standard way to document this

2021-12-09 06:30 UTC, wkopen commented on __tests__/unit/test_datetime_parser.py
> +    **format_list_test_cases,
We are in `parse_with_no_format_list_test_cases` but you are adding formatted test cases. It's inconsistent with the name of this test case.

2021-12-09 06:30 UTC, wkopen commented on __tests__/unit/test_datetime_info.py
> +    ("1:2:32 20-12-1 AM America/Chicago", "01-12-2020 01:02:32 AM America/Chicago"),
I'm not sure I understand this. I assume the original string means YY-MM-DD. But in your expected string it's DD-MM-YYYY? What's the purpose of converting it from a non-confusing form to a confusing form?

2021-12-09 06:30 UTC, wkopen commented on __tests__/unit/test_datetime_parser.py
> +import pytest
I assume `test_datetime_parser.py` is more like a unit test but this file is more like an integration test. I'm looking for more formats covered in integration tests actually just like what you had in unit tests.

And, if this file serves more like a integration test, we should probably move it to `__tests__/integration`. If this file is not an integration test, I'm looking for an integration (end-to-end) test file. In the integration test, if you can also include the format with `Z` in the end that will be great because in most cases people will be using the UTC+0 ISO format in the IDS JSON.

2021-12-09 12:39 UTC, setiat commented on __tests__/unit/test_datetime_parser.py
> +format_list_test_cases = {
renamed it to `datetime_formats_list_test_cases`

2021-12-09 12:39 UTC, setiat commented on task_script_utils/datetime_parser/datetime_config.py
> +        # The "fold" is required during the 2 hour window when clocks are set back in
added doc strings

2021-12-09 12:40 UTC, setiat commented on __tests__/unit/test_datetime_parser.py
> +    **format_list_test_cases,
Fixed it 
and renamed the variable to `parse_with_no_datetime_formats_list_test_cases`

2021-12-09 12:41 UTC, setiat commented on __tests__/unit/test_datetime_info.py
> +    ("1:2:32 20-12-1 AM America/Chicago", "01-12-2020 01:02:32 AM America/Chicago"),
Fixed DatetimeInfo code to always return date in Year-month-day

2021-12-14 14:01 UTC, setiat commented
> > @robjhornby-ts, @wkopen: Should we be able to parse just dates or just times, e.g.:
> > ```python
> > parse('2021-12-08')
> > parse('12:49:51')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or should those produce errors?
> 
> Yes I think there are cases where only date or time is provided. It's not a common case though. Let's make a separate ticket for it and document in the README it's a limitation. Not required in this version.

added as a limitation to readme

2021-12-15 12:53 UTC, mlipschultz requested changes
Just one fairly small request, then I think it should be good to merge.

2021-12-15 12:53 UTC, mlipschultz commented on task_script_utils/datetime_parser/ts_datetime.py
> +        microseconds = self._subseconds[:6]
Won't this fail with a TypeError if `self._subseconds` is None?  From the `__init__`, it looks like that's an expected value for `self._subseconds`.

2021-12-16 05:51 UTC, wkopen requested changes
Hi @setiat , I think the most important observation from reviewing the test cases is "we don't have a clear spec doc on the parser behavior under different situations". You can see my specific comments in the README.md file. Without a clear spec doc, nobody can clearly tell what the parser will do under certain situations. It's not completely on you to be fair. The Confluence page we have is also not documented clearly.

So I recommend starting from the README.md. Just write out the spec doc as I suggested, then return to me for another review before you change any code. Once the spec doc is good, you can go ahead modifying the code and tests. Let's don't rush it. I know this task has been worked on for a while. We (Rob, Mike and I) take the responsibility of not giving you a much earlier review on the design.

2021-12-16 05:51 UTC, wkopen commented on __tests__/integration/test_convert_to_iso.py
> +    ("01/02/03 04:03:00 America/New_York", None, False, None),
Please see my suggestion in README on how to organize test cases

2021-12-16 05:51 UTC, wkopen commented on __tests__/integration/test_convert_to_iso.py
> +    ("2021/11/07 04:03:00 America/New_York", None, None, None),
I'm curious why we can't parse this. I've never seen in any date format YYYY/DD/MM. I don't think it exists. Theoretically it can, but in reality it never does. Please see this wikipedia: https://en.wikipedia.org/wiki/Date_format_by_country#

2021-12-16 05:51 UTC, wkopen commented on README.md
> +- `day_first`: `True/False/None`
Please specify if it's optional or required and if optional what's the default value. It's very standard in API docs. I think default is `None` but better to specify.

2021-12-16 05:51 UTC, wkopen commented on README.md
> +- `year_first`: `True/False/None`
We should explicitly say if `year_first` is `True`, then we assume the format will be YMD because there is no YDM format in any country. It's a very safe assumption and backed by https://en.wikipedia.org/wiki/Date_format_by_country#

2021-12-16 05:51 UTC, wkopen commented on README.md
> +| day_first(down)/ year_first | True     | False                  | None                                 |
This matrix is confusing because of the way it's formatted. I think it's better to just have `day_first` `year_first` on different columns and `resolution` column. It's also better to use single character like YMD instead of YY-MM-DD. I assume you just want to present the order instead of format. YY-MM-DD in some context is a format and it also implies two-digit year value.

2021-12-16 05:51 UTC, wkopen commented on README.md
> +| **True**                    | YY-DD-MM | DD-MM-YY               | DD-MM-YY                             |
YDM order never exists. This is a safe assumption and should be documented.

2021-12-16 05:51 UTC, wkopen commented on README.md
> +### DatetimeConfig
* I would say most people don't care about this config. They just want our date time conversion to work. So before we introduce this config, we should list out all unambiguous formats which doesn't need any config. And we should also list out all ambiguous formats that will require this additional config otherwise we can't parse it.
* This should also determine how we organize our test cases. The two main parts should be "unambiguous" and "ambiguous". Then in "ambiguous", we should group by date time format. For example, you want to test `21-12-12T13:00:00`, it's nice to do none of the config defined, then move on to only `year_first` is defined, only `day_first` is defined, only `tz_dict` is defined. Then move to 2 of the configs defined, then move to all 3 defined. This way, the tests are organized in a permutation order.
* If the date time is already "unambiguous", will config do anything to it? It's also worth documenting the behavior.

2021-12-16 05:51 UTC, wkopen commented on __tests__/unit/test_datetime_info.py
> +    ("01/02/03", True, True, "2001-03-02"),
Please see my comments in the README about how to order the test cases. It's very hard to follow right now.

2021-12-16 05:51 UTC, wkopen commented on __tests__/integration/test_convert_to_iso.py
> +    ("2021/11/14 04:03:00 America/New_York", None, True, None),
This is also my question in README, what's our behavior if the date time is already unambiguous. It's important to document the behavior.

2021-12-16 05:51 UTC, wkopen commented on __tests__/integration/test_convert_to_iso.py
> +    ("13/02/03 04:03:00 America/New_York", None, None, None),
This is an unambiguous format. 13 can never be a month value, so it's implicit that it's DDMMYY. I think countries use 2-digit year in the beginning is very rare according to Wiki (probably just Kenya). So we should make it a safe assumption.

2021-12-16 05:51 UTC, wkopen commented on __tests__/integration/test_convert_to_iso.py
> +    ("01/15/11 04:03:00 America/New_York", None, True, None),
This is also an unambiguous format, 15 can never be a month value, so it's implicit that the format is MMDDYY. So we should be able to parse it. Again, all of this is due to we don't have a clear spec on what's our parser expected behavior

2021-12-16 20:10 UTC, robjhornby-ts commented on README.md
> +| **True**                    | YY-DD-MM | DD-MM-YY               | DD-MM-YY                             |
That just means people should almost never define `day-first` `True` & `year-first` `True` in their datetime config; but it is possible and this is the resulting format

2021-12-16 20:10 UTC, robjhornby-ts commented on __tests__/integration/test_convert_to_iso.py
> +    ("13/02/03 04:03:00 America/New_York", None, None, None),
I've seen 2 digit years first in a plenty of software even if it's not an official country format, e.g. it's one of the Windows date formats, which means Empower data could have this format depending on the settings of the PC generating it. (That makes this an ambiguous format)

includes `yy/MM/dd`:
![image](https://user-images.githubusercontent.com/80261803/146441716-407e98ad-665d-4258-9b46-23f514e48728.png)

2021-12-16 20:10 UTC, robjhornby-ts commented on __tests__/integration/test_convert_to_iso.py
> +    ("01/15/11 04:03:00 America/New_York", None, True, None),
as above, could be YYMMDD

2021-12-16 20:10 UTC, robjhornby-ts commented on __tests__/integration/test_convert_to_iso.py
> +    ("2021/11/07 04:03:00 America/New_York", None, None, None),
Agreed on this one, 4 digit year first -> assume YYYYMMDD

2021-12-18 17:20 UTC, wkopen commented on __tests__/integration/test_convert_to_iso.py
> +    ("13/02/03 04:03:00 America/New_York", None, None, None),
You are right Rob. Please ignore what I said here. It is ambiguous.

2021-12-18 17:21 UTC, wkopen commented on __tests__/integration/test_convert_to_iso.py
> +    ("01/15/11 04:03:00 America/New_York", None, True, None),
But here we know it can only be MDY because YDM never exists.

2021-12-18 17:24 UTC, wkopen commented on README.md
> +| day_first(down)/ year_first | True     | False                  | None                                 |
I agree

2022-01-24 18:20 UTC, mlipschultz reviewed
Two minor suggestions for improvement.

2022-01-24 18:20 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +    def _try_formats(self, date_str: str, formats: Tuple[str]):
[minor] Just so the type checker knows it's ok to have more than one string in the tuple, although I think you don't need to require a `Tuple`, but rather a more generic type (`Iterable`?)

```suggestion
    def _try_formats(self, date_str: str, formats: Tuple[str, ...]):
```

2022-01-24 18:20 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +        sure only one of the format successfully parses the date.
[minor]
```suggestion
        """Given a date string and a list for formats, make sure
        only one of the format successfully parses the date.
```

2022-01-26 13:46 UTC, mlipschultz reviewed
I found some typos to fix and a case where black made a bad formatting decision.  Plus, it looks like there are still some unaddressed review comments from earlier.

2022-01-26 13:46 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +            date_fmt = f"{self.token_month} " f"{self.token_day} " f"YYYY"
I'm guessing black auto-formatted this weird, but could you fix it to be more readable:
```suggestion
            date_fmt = f"{self.token_month} {self.token_day} YYYY"
```

2022-01-26 13:46 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_info.py
> +                # This is validate later below in this function.
```suggestion
                # This is validated later below in this function.
```

2022-01-26 13:46 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_config.py
> +        It also provide an options to handle abbreviated time zones and
```suggestion
        It also provides an option to handle abbreviated time zones and
```

2022-01-26 13:46 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_config.py
> +        passed to task scripts
```suggestion
        passed to task scripts.
```

2022-01-26 13:46 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_config.py
> +            by `DatetimeInfo` class.
Both `day_first` and `year_first` claim to interpret the first value as day or year.  Can you add something to the docstring to clarify what happens?  If they're both true, then `year_first` takes priority and `day_first` starts with the second value, right?

2022-01-27 07:05 UTC, setiat commented on task_script_utils/datetime_parser/datetime_config.py
> +        It also provide an options to handle abbreviated time zones and
fixed.

2022-01-27 07:05 UTC, setiat commented on task_script_utils/datetime_parser/datetime_config.py
> +        passed to task scripts
fixed,

2022-01-27 07:06 UTC, setiat commented on task_script_utils/datetime_parser/datetime_config.py
> +            by `DatetimeInfo` class.
Updated doc strings and Yes, the resulting format will be Y-D-M

2022-01-27 07:09 UTC, setiat commented on task_script_utils/datetime_parser/ts_datetime.py
> +        microseconds = self._subseconds[:6]
it was already fixed : https://github.com/tetrascience/ts-task-script-utils/blob/DE-2591-datetime-parser/task_script_utils/datetime_parser/ts_datetime.py#L28

Not sure why it is  not tagged as  outdated

2022-01-27 07:12 UTC, setiat commented on README.md
> +# Parse() returns a TSDatetime Object.
fixed. Moved it out of code block

2022-01-27 07:13 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            date_fmt = f"{self.token_month} " f"{self.token_day} " f"YYYY"
fixed

2022-01-27 07:13 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +                # This is validate later below in this function.
fixed

2022-01-27 07:54 UTC, setiat commented
@mlipschultz To pass the PR checks, I have to restrict python version to 3.7. This applies to both travis build and GitHub hooks. Prior to black it was running on 3.7 and during its introduction, `requires` was removed from Pipfile. I could not make it work without restring the python version.

All other comments were also addressed.

2022-01-27 12:56 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_config.py
> +        passed to task scripts
It's minor, but you deleted the `s` instead of adding the `.`

2022-01-27 12:57 UTC, mlipschultz commented on task_script_utils/datetime_parser/datetime_config.py
> +        It also provide an options to handle abbreviated time zones and
You still need to add an `s` to `provide`

2022-01-27 13:43 UTC, setiat commented on task_script_utils/datetime_parser/datetime_config.py
> +        It also provide an options to handle abbreviated time zones and
fixed 😅

2022-01-27 13:43 UTC, setiat commented on task_script_utils/datetime_parser/datetime_config.py
> +        passed to task scripts
fixed

2022-01-27 14:13 UTC, mlipschultz requested changes
I went through all unresolved comments and resolved the ones that looked addressed (sorry Kai and Rob if you wanted to resolve your own comments).  I left a few more comments to address.

@wkopen, I'd like you to take a look at these comments in particular.  You had some questions about test cases vs. spec and I tried to follow the spec to confirm test case behavior.
* https://github.com/tetrascience/ts-task-script-utils/pull/2/files#r770240480
* https://github.com/tetrascience/ts-task-script-utils/pull/2/files#r770239247 -- I think this reveals a mismatch between the spec and the code

Since I couldn't respond to some comments, here are the comments any my questions:

https://github.com/tetrascience/ts-task-script-utils/pull/2#discussion_r770231421
> * I would say most people don't care about this config. They just want our date time conversion to work. So before we introduce this config, we should list out all unambiguous formats which doesn't need any config. And we should also list out all ambiguous formats that will require this additional config otherwise we can't parse it.
> * This should also determine how we organize our test cases. The two main parts should be "unambiguous" and "ambiguous". Then in "ambiguous", we should group by date time format. For example, you want to test `21-12-12T13:00:00`, it's nice to do none of the config defined, then move on to only `year_first` is defined, only `day_first` is defined, only `tz_dict` is defined. Then move to 2 of the configs defined, then move to all 3 defined. This way, the tests are organized in a permutation order.
> * If the date time is already "unambiguous", will config do anything to it? It's also worth documenting the behavior.

I don't know that we ever list out all unambiguous formats.  It wasn't obvious in the spec.  Is it there and I'm just missing it?  If it's not there, is it still useful to have?

https://github.com/tetrascience/ts-task-script-utils/pull/2#discussion_r770882278
> This table is for 2 digit years as far as I understand. A 4 digit year should never depend on the "year-first" config value.
> 
> Maybe we need a separate table for 4 digit years, but I think it would be a subset of this table (i.e. everywhere we have `year-first` `True` in the table corresponds to a 4-digit-year-format of `YYYY-XX-XX`; anywhere with `year-first` `False` corresponds to `XX-XX-YYYY`; anywhere with `year-first` `None` isn't included because a 4 digit year is unambiguous)

We have no table for 4-digit years.  Do we still want one?

https://github.com/tetrascience/ts-task-script-utils/pull/2#discussion_r770229088
> We should explicitly say if `year_first` is `True`, then we assume the format will be YMD because there is no YDM format in any country. It's a very safe assumption and backed by https://en.wikipedia.org/wiki/Date_format_by_country#

We never say why YDM is not a valid format when `year_first` is True.  Is it still important to do so?  At one time you thought it was because you even [mention it again](https://github.com/tetrascience/ts-task-script-utils/pull/2#discussion_r770230574).

2022-01-27 15:21 UTC, setiat commented on README.md
> +  - [Limitations](#limitations)
fixed.

2022-01-27 15:21 UTC, setiat commented on __tests__/integration/test_datetime_parser.py
> +    except Exception as e:
fixed.

2022-01-27 15:21 UTC, setiat commented on task_script_utils/datetime_parser/README.md
> +![Short date format Resolution for two digit date parts](./short-date-format-resolution.png)
fixed

2022-01-27 15:26 UTC, setiat commented on setup.py
> +VERSION = "1.2.0"
I wanted to go for 1.1.0 but then there is a ticket DE-2985 that says release v1.2.0.
Should I change it to 1.1.0?

2022-01-27 15:29 UTC, setiat commented on __tests__/integration/test_datetime_parser.py
> +    except Exception as e:
The explicit datetime config, make it un-parsable in this case.
But if user does not specify any datetime config or explicitly set year_first and day_first to None, it will be parsed as `2021-11-14T04:03:00-05:00`

2022-01-27 15:32 UTC, setiat commented on task_script_utils/datetime_parser/datetime_info.py
> +            date_fmt = date_fmt = f"{self.token_month} {self.token_day} YYYY"
fixed

2022-01-27 15:42 UTC, mlipschultz commented on setup.py
> +VERSION = "1.2.0"
Yes.  I don't know why I wrote 1.2.0 in the ticket, sorry!

2022-01-27 15:45 UTC, mlipschultz commented on __tests__/integration/test_datetime_parser.py
> +    except Exception as e:
According to the flow chart, if we make it to "Try Regex parsing using DatetimeInfo" (which we do for this case) it says "If config is passed to parse(), it will be used to resolve ambiguity when inferring date".  In this case, I don't think there is any ambiguity so it shouldn't need to consult config.

2022-01-27 15:59 UTC, setiat commented on setup.py
> +VERSION = "1.2.0"
Changed it v1.0.0

2022-01-31 09:29 UTC, setiat commented on __tests__/integration/test_datetime_parser.py
> +    except Exception as e:
The readme and flow chart have now been updated to indicated that if `DatetimeConfig` is present, it has higher precedence.

2022-01-31 13:21 UTC, mlipschultz approved these changes
I have one minor comment regarding wording, but everything looks good to merge!

2022-01-31 13:21 UTC, mlipschultz commented on task_script_utils/datetime_parser/README.md
> +- `config: DatetimeConfig (optional)`: You also have an options to pass `DatetimeConfig`. It provides complementary information on how to mark parsed digits as day, month or year and also provide an
[minor]
```suggestion
- `config: DatetimeConfig (optional)`: You also have an options to pass `DatetimeConfig`. It provides complementary information on how to mark parsed digits as day, month or year and also provide options to handle abbreviated time zones and fold for parsing ambiguous timestamps during daylight saving transitions. Ideally, DatetimeConfig should be constructed from pipeline configuration passed to task scripts
```

2022-01-31 15:05 UTC, wkopen approved these changes
@mlipschultz I didn't look too close. But many of my comments have been addressed in another PR I believe. Thus approving this.

2022-02-01 07:31 UTC, merged