EP-0: Publish package to JFrog Artifactory
tetrascience/ts-task-script-utils pull request #23
Opened 2022-04-20 20:46 UTC by aslotte

## JIRA Ticket

- [ ] PR Title should be in the form: "DE-12345: Short Description of Changes"

## Description of Changes

## General

- [ ] Not applicable
- [ ] Changelog is added in README.md
  - [ ] Changes are at a high level and do not reference code directly
  - [ ] Scanned for spelling errors (eg. "Code Spell Checker" in VS Code)

### Testing Completed

- [ ] Tested manually locally
- [ ] Unit tests updated
- [ ] Integration tests updated
- [ ] None (please explain)

## Related Information

## Description

## Supporting test data

## Automated testing

- [ ] Unit tests
- [ ] Integration tests
- [ ] API tests
- [ ] End-To-End tests
- [ ] N/A (please clarify)

2022-04-21 10:59 UTC, mlipschultz approved these changes

2022-04-21 12:11 UTC, aslotte commented
Thanks for the ✅ @mlipschultz! :) Let's not merge this one just yet though as it's a PoC and we'll probably at least change the secret names (e.g. moving them to org secrets)

2022-04-22 16:57 UTC, mlipschultz requested changes
The README file needs to be updated

2022-04-22 16:57 UTC, mlipschultz commented on README.md
>  - [Test](#test)
This section still references `pipenv`, even though the project has migrated to `poetry`.

2022-04-22 19:56 UTC, VladimirShteyn commented on README.md
>  - [Test](#test)
Fixed by deleting the `## Test` section. Environment setup and automated testing is in CONTRIBUTING.md.

2022-04-29 11:42 UTC, mlipschultz requested changes

2022-04-29 11:42 UTC, mlipschultz commented on pyproject.toml
> +version = "1.1.2"
[We're now at 1.2.0](https://github.com/tetrascience/ts-task-script-utils/blob/master/pyproject.toml#L9)

2022-05-04 17:32 UTC, VladimirShteyn commented on pyproject.toml
> +version = "1.1.2"
-  [ ] bump package version by running `poetry version 1.2.0`

2022-07-13 17:13 UTC, closed without merging