DE-3695: Prepare for v1.2.0 release
tetrascience/ts-task-script-utils pull request #25
Opened 2022-04-27 13:49 UTC by abclay

## JIRA Ticket

https://tetrascience.atlassian.net/browse/DE-3695

- [x] PR Title should be in the form: "DE-12345: Short Description of Changes"

## Description of Changes

* Updated version number in `setup.py`
* Ran `pipenv upgrade` to get latest versions in lock file
* Ran `pipenv lock -r > requirements.txt` to get latest requirements for publishing

## General

- [x] Not applicable
- [ ] Changelog is added in README.md
  - [ ] Changes are at a high level and do not reference code directly
  - [ ] Scanned for spelling errors (eg. "Code Spell Checker" in VS Code)

### Testing Completed

- [x] Tested manually locally
- [ ] Unit tests updated
- [ ] Integration tests updated
- [ ] None (please explain)

## Related Information

<!--
Please list any related information here.
For example: links to other PRs, link to IDS, link to confluence docs, etc
--!>

2022-04-27 14:04 UTC, VladimirShteyn requested changes
We're pinning dependency versions in the setup.py file, which is a big no-no. [link to code](https://github.com/tetrascience/ts-task-script-utils/pull/25/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R12-R15). can we fix that in this PR? It's caused dependency conflict issues for DI Team members. It would be unfortunate if we propagated this issue to v1.2.0.

2022-04-27 14:13 UTC, abclay commented
> We're pinning dependency versions in the setup.py file, which is a big no-no. [link to code](https://github.com/tetrascience/ts-task-script-utils/pull/25/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R12-R15). can we fix that in this PR? It's caused dependency conflict issues for DI Team members. It would be unfortunate if we propagated this issue to v1.2.0.

Makes sense to me.  I'll look into how to fix.

2022-04-27 20:42 UTC, abclay commented
I switched the dependency management from pipenv to poetry.  `poetry publish` is so easy!

I also fixed the `black` issue I introduced (wrong place to make the line length long...) and removed the Travis integration.

2022-04-27 21:39 UTC, VladimirShteyn approved these changes
Good work. Very clean.

2022-04-27 21:39 UTC, VladimirShteyn commented on pyproject.toml
> +numpy = "^1.21.0"
[minor] We could loosen this to `>=1.17.0,<2`. I don't see any features in `ts-task-script-utils` that require a version higher than `1.17.0`.

2022-04-27 21:42 UTC, VladimirShteyn commented on pyproject.toml
> +numpy = "^1.21.0"
I just noticed that one of the dependencies is `pytest-cov`. It causes issues running individual tests. Perhaps we should include the following text in README.md or CONTRIBUTING.md?

```markdown
## Running tests

`ts-task-script-utils` uses `pytest` as its testing framework. As such, tests can be executed with the `pytest` shell command (see the [pytest docs here](https://docs.pytest.org/en/latest/how-to/usage.html)). Note that `pytest-cov`, a `pytest` plugin dependency of `ts-task-script-utils`, prevents one from running individual tests; any attempt to run a single test runs the entire test module. To turn off `pytest-cov` and thus enable running individual tests, pass the `--no-cov` flag to the `pytest` command. For example, to run the `TestMyExampleClass.test_my_examle_method` test located at `tests/test_my_module.py`, do

```shell
pytest --no-cov tests/test_my_module.py::TestMyExampleClass::test_my_examle_method
```
```

2022-04-28 12:33 UTC, abclay commented on pyproject.toml
> +numpy = "^1.21.0"
I don't think that running tests belongs in the README, since that goes straight onto PyPI.  I think creating a CONTRIBUTING file is outside the scope of this effort, but I do think it's something worth doing.  Would you mind creating a ticket for that?

2022-04-28 12:56 UTC, mlipschultz approved these changes

2022-04-28 15:13 UTC, VladimirShteyn commented on pyproject.toml
> +numpy = "^1.21.0"
Can do.

2022-04-28 15:24 UTC, merged