DE-3885: Implement parsing functions
tetrascience/ts-task-script-utils pull request #28
Opened 2022-05-19 16:07 UTC by VladimirShteyn

## JIRA Ticket
https://tetrascience.atlassian.net/browse/DE-3885

## Description of Changes
Updated the implementation of the parsing functions, mostly by deleting the research implementations. The only major change in logic was improving the error message of `to_boolean`.

## General

- [ ] Not applicable
- [ ] Changelog is added in README.md
  - [ ] Changes are at a high level and do not reference code directly
  - [ ] Scanned for spelling errors (eg. "Code Spell Checker" in VS Code)

### Testing Completed

- [ ] Tested manually locally
- [ ] Unit tests updated
- [ ] Integration tests updated
- [ ] None (please explain)

## Related Information

## Description

## Supporting test data

## Automated testing

- [ ] Unit tests
- [ ] Integration tests
- [ ] API tests
- [ ] End-To-End tests
- [ ] N/A (please clarify)

2022-05-19 17:26 UTC, abclay reviewed
Couple quick questions from me.  I will hold off on approving because I wrote the original code and someone else should sign off.

2022-05-19 17:26 UTC, abclay commented on __tests__/unit/parse_functions/test_to_boolean.py
> +    """Tests for cases where `to_boolean` raises an exception."""
Is this to make testing in your IDE easier?  I understand the desire to group tests, but I'm not a big fan of having to add `@staticmethod` for all the test functions.

2022-05-19 17:26 UTC, abclay commented on pyproject.toml
>  pandas = "1.3.5"
Are numpy and pandas still dependencies in this library?  I don't remember.

2022-05-19 17:36 UTC, mlipschultz requested changes
There's one or two deviations from our agreed-upon plan for v1.  I think those should be fixed.  I also have a couple of other small improvements suggested.

2022-05-19 17:36 UTC, mlipschultz commented on task_script_utils/parse.py
> +        true_set_quoted_items = [f"'{true_value}'" for true_value in true_set]
What's the reason for quoting the values for this error?  Could the message for `ValueError` just be:
```python
        raise ValueError(
            f"The set of 'true' values and 'false' values cannot be empty. "
            f"true_set: {true_set}. "
            f"false_set: {false_set}"
        )
```

2022-05-19 17:36 UTC, mlipschultz commented on task_script_utils/parse.py
> +            return string.casefold()
:trophy:

2022-05-19 17:36 UTC, mlipschultz commented on task_script_utils/parse.py
> +    false_set_compare: Set[str] = set(false_set_compare)
Why convert the keys into a set before doing the contains check?

2022-05-19 17:37 UTC, mlipschultz commented on pyproject.toml
>  pandas = "1.3.5"
Numpy is [currently a dependency](https://github.com/tetrascience/ts-task-script-utils/blob/master/pyproject.toml#L30), but not pandas.

2022-05-19 17:51 UTC, VladimirShteyn commented on .gitignore
> +**/.python-version
`.python-version` is a file used by `pyenv` to specify the folder's version of Python.

2022-05-19 17:52 UTC, VladimirShteyn commented on pyproject.toml
>  pandas = "1.3.5"
Done.

2022-05-19 17:57 UTC, VladimirShteyn commented on task_script_utils/parse.py
> +            if np.isclose(int_val, float_val):
In some cases, this implementation is consistent with our earlier decision and in others it's not. Could `float("1")` be evaluated to `1.000000000000001` on some systems, thus erroneously returning `None`? That said, I agree, `None` is the agreed return value when the user passes `to_int("1.000000000000001")`.

2022-05-19 17:58 UTC, VladimirShteyn commented on task_script_utils/parse.py
> +        true_set_quoted_items = [f"'{true_value}'" for true_value in true_set]
Yeah, let's keep it simple. Sometimes it's helpful to visually separate values with quotes, but the commas already do that.

2022-05-19 17:59 UTC, VladimirShteyn commented on task_script_utils/parse.py
> +    false_set_compare: Set[str] = set(false_set_compare)
Good point!

2022-05-19 18:02 UTC, VladimirShteyn commented on __tests__/unit/parse_functions/test_to_boolean.py
> +    """Tests for cases where `to_boolean` raises an exception."""
Yes, and to make the test names shorter and thus easier to read. I've configured PyCharm to use a test template, so adding `@staticmethod` is no extra work. One can also use a vanilla instance method for tests too, but that's an extra `self` to type. Not sure which is worse.

2022-05-19 18:14 UTC, VladimirShteyn commented on task_script_utils/parse.py
> +            if np.isclose(int_val, float_val):
I changed `math.isclose(int_val, float_val)` to `int_val == float_val`.

2022-05-19 18:39 UTC, mlipschultz commented on task_script_utils/parse.py
> +            if np.isclose(int_val, float_val):
Did you push that change yet?  I'm still seeing `math.isclose`.

I agree though that we might want to discuss what "close enough" is in a future iteration.

2022-05-20 13:35 UTC, mlipschultz approved these changes

2022-05-20 13:46 UTC, VladimirShteyn commented on pyproject.toml
>  pandas = "1.3.5"
I found I could remove `numpy` as a dependency and the tests still pass. 🎉

2022-05-20 13:47 UTC, merged