DE- 2591: handle z in raw datetime
tetrascience/ts-task-script-utils pull request #6
Opened 2021-12-10 05:46 UTC by setiat

- Handle raw datetimes with time ending in Z..eg 12:30:00Z
- Locked pendulum version
- Fixed a bug in sub second, updated test cases
  - Bug: input = 12-12-12T12:12:12, formats = [YY-MM-DDTHH:MM:SS] with give an output like 12-12-12T12:12:12.0
  - The subsencond = 0 was the bug, fixed now
- Updated convert to iso test cases.... added test cases from google doc

2021-12-10 14:13 UTC, mlipschultz requested changes

2021-12-13 12:31 UTC, setiat commented on __tests__/unit/test_convert_to_iso.py
> +    ("01/02/13T04:03:00 America/New_York", False, True, "2013-02-01T09:03:00Z"),
Fixed

2021-12-13 12:32 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +        sub_seconds_pattern = r"[:]{1}(\d{1,2})[.]{1}(\d+)"
Changed logic for sub seconds handling.

2021-12-13 12:32 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +        sub_seconds_pattern = r"[:]{1}(\d{1,2})[.]{1}(\d+)"
regex not needed

2021-12-13 12:32 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +            subseconds = sub_seconds_matches.groups()[1]
same as  above comment

2021-12-13 12:34 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
>          subseconds = parts["microsecond"]
- `parts` is used to build `TSDatetime._datetime`
- `subseconds` is used to populate `TSDatetime._subseconds`

2021-12-13 12:35 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +    return "".join(char_list[:-1])
I changed the code ... but some test cases failed.
will take this up later ... refine the regex more to check if it can be used to cover all the cases

2021-12-13 12:35 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +        # it will be truncated to 6 digits
updated the code and added some test cases

2021-12-13 12:35 UTC, setiat commented on task_script_utils/datetime_parser/ts_datetime.py
> +        microseconds = int(self._subseconds)[:6]
updated the code and added some test cases

2021-12-13 13:31 UTC, mlipschultz commented on task_script_utils/datetime_parser/utils.py
> +    return "".join(char_list[:-1])
Looks like I forgot to handle the end-of-string case.  This passes all the tests:
```python
return re.sub(r'(?<=\d|\s)Z(?=\s|$)', '+00:00', datetime_str)
```

2021-12-13 14:03 UTC, setiat commented on task_script_utils/datetime_parser/utils.py
> +    return "".join(char_list[:-1])
added.

2021-12-13 14:23 UTC, mlipschultz approved these changes

2021-12-13 14:23 UTC, merged