DE-2591 refactor
tetrascience/ts-task-script-utils pull request #8
Opened 2021-12-17 13:05 UTC by setiat

2021-12-17 18:36 UTC, mlipschultz reviewed
I know this is a WIP, but I took a look because I had some time.  I didn't finish reviewing, but wanted to share my comments anyway.

2021-12-20 06:49 UTC, setiat commented on __tests__/integration/test_parse.py
> +    ("12-13-12T12:12:12Z", True, None, None),
Nice point! I don't remember the reason but we decided that `year_first=True` and `day_first=None` should result into `YY-MM-DD`, at per the final resolution matrix and I think it should be the same when year is 4 digits long.
This means `("2021-13-12T12:12:12Z", None, None, "2021-12-13T12:12:12+00:00")` should return None as it is non  parsable

This also means following test cases are wrong and needs to be altered. My Bad!
```python
FAILED __tests__/integration/test_parse.py::test_parse[2021-13-12T12:12:12Z-None-None-2021-12-13T12:12:12+00:00] - AssertionError: assert None == '2021-12-13T12:12:12+00:00'
FAILED __tests__/integration/test_parse.py::test_parse[2021-13-12T12:12:12 America/Chicago-None-None-2021-12-13T12:12:12-06:00] - AssertionError: assert None == '2021-12-13T12:12...


FAILED __tests__/unit/test_datetime_info.py::test_regex_parsing[2018-13-09 16:15+2 PM-2018-09-13 16:15:00 +02:00] - AssertionError: assert None == '2018-09-13 16:15:00 +02:00'
FAILED __tests__/unit/test_datetime_info.py::test_regex_parsing[2018-13-09T11:12:23.000-05:30-2018-09-13 11:12:23.000 -05:30] - AssertionError: assert None == '2018-09-13 11:12:2...
FAILED __tests__/unit/test_datetime_info.py::test_regex_parsing[2018-13-09 11:12:23.000+05:30-2018-09-13 11:12:23.000 +05:30] - AssertionError: assert None == '2018-09-13 11:12:2...
FAILED __tests__/unit/test_datetime_info.py::test_regex_parsing[2018-13-09T01:15+14 PM-2018-09-13 01:15:00 PM +14:00] - AssertionError: assert None == '2018-09-13 01:15:00 PM +14...
FAILED __tests__/unit/test_datetime_info.py::test_regex_parsing[2018-13-09T16:15-14 PM-2018-09-13 16:15:00 -14:00] - AssertionError: assert None == '2018-09-13 16:15:00 -14:00'
FAILED __tests__/unit/test_datetime_info.py::test_regex_parsing[2018-13-09T16:15 +05:30 PM-2018-09-13 16:15:00 +05:30] - AssertionError: assert None == '2018-09-13 16:15:00 +05:30'
FAILED __tests__/unit/test_datetime_info.py::test_regex_parsing[2018-13-09T16:15+5:30 PM-2018-09-13 16:15:00 +05:30] - AssertionError: assert None == '2018-09-13 16:15:00 +05:30'
FAILED __tests__/unit/test_datetime_info.py::test_regex_parsing[2018-13-09T16:15-0530 PM-2018-09-13 16:15:00 -05:30] - AssertionError: assert None == '2018-09-13 16:15:00 -05:30'
FAILED __tests__/unit/test_datetime_info.py::test_regex_parsing[2018-13-09T16:15 CST PM-2018-09-13 16:15:00 -06:00] - AssertionError: assert None == '2018-09-13 16:15:00 -06:00'
FAILED __tests__/unit/test_datetime_info.py::test_regex_parsing[2018-13-09T16:15:4.15 +05:30 PM-2018-09-13 16:15:04.15 +05:30] - AssertionError: assert None == '2018-09-13 16:15:
```

I will modify them.

2021-12-20 07:01 UTC, setiat commented on __tests__/integration/test_parse.py
> +    ("12-13-12T12:12:12Z", True, None, None),
on second thought and as per [this](https://tetrascience.slack.com/archives/C02FBRVTLS1/p1639682489020600) conversation, I think `("12-13-12T12:12:12Z", True, None, None),` should return YY-DD-MM

and **resolution matrix needs to be updated** So that its consistent for 4 digit year cases and 2 digit year cases

I will work on this

2021-12-20 13:36 UTC, setiat commented on __tests__/integration/test_parse.py
> +    ("2021-13-13T12:12:12 America/Chicago", None, False, None),
fixed

2021-12-20 13:36 UTC, setiat commented on __tests__/integration/test_parse.py
> +# Note: For short dates with 4 digits year, DatetimeConfig.year_first is ignored
added

2021-12-20 13:37 UTC, setiat commented on __tests__/integration/test_parse.py
> +    ("12-13-12T12:12:12Z", True, None, None),
fixed as per my last comment..

2021-12-21 13:25 UTC, mlipschultz commented on README.md
> +| day_first(down)/ year_first | True                   | False                  | None                                 |
Just a reminder that [Kai found this table layout confusing](https://github.com/tetrascience/ts-task-script-utils/pull/2#discussion_r770229388).  I think he would prefer to see:
```suggestion
| `day_first` | `year_first` | Format |
| True        | True         | YY-DD-MM |
...
```

2021-12-21 13:25 UTC, mlipschultz commented on README.md
> +  - Whether to interpret the first value in an ambiguous 3-integer date (e.g. 01/05/09) as the year.
Since you're defining the config here, I think you should also say here that it's ignored when the year is four digits.  I know you imply it (it's not ambiguous if there's a four-digit integer), but pointing it out could be helpful.  Maybe:
```suggestion
  - Whether to interpret the first value in an ambiguous 3-integer date (e.g. 01/05/09) as the year.  When the year is specified in four digits, this configuration is ignored.
```

2021-12-21 13:25 UTC, mlipschultz commented on __tests__/integration/test_parse.py
> +# Note: For short dates with 4 digits year, DatetimeConfig.year_first is ignored
Can you point me to the test cases?  I'm not seeing them

2021-12-23 13:28 UTC, setiat commented on spec.md
> +`taskscript_utils.datetime_parser` exposes `parse()` and `convert_to_ts_iso8601()` methods for parsing string datetimes.
removed.

2021-12-23 13:28 UTC, setiat commented on task_script_utils/datetime_parser/parser.py
> +    #if not parsed_datetime:
yup..removed.

2021-12-23 13:39 UTC, setiat commented
@mlipschultz @wkopen Made the required changes to spec.md.
Let me know if it looks complete to you.

2021-12-23 17:25 UTC, mlipschultz requested changes
I know I left a lot of comments.  Most of them are fixing typos or other minor things.

2021-12-23 17:25 UTC, mlipschultz commented on spec.md
> +| May 26th 2013 12:12:12.5677 AM Asia/Kolkata         | 2013-05-26T00:12:12.0001+05:30   |                                                       |
Why would the sub-second time go from `5677` to `0001`?

2021-12-23 17:25 UTC, mlipschultz commented on spec.md
> +| 21-23-2020T12:13:14                        | Year = 2020, but Can't decide day and month between: ('21', '23')                                 |
```suggestion
| 21-23-2020T12:13:14                        | Year = 2020, but can't decide day and month between: ('21', '23')                                 |
```

2021-12-23 17:25 UTC, mlipschultz commented on spec.md
> +| False      | True      | day-month-year                                         |
I know this is very minor, but could you swap these two rows so day_first always goes: True, False, None?

2021-12-23 17:25 UTC, mlipschultz commented on spec.md
> +| None       | None      | month-day-year <br> day-month-year <br> year-month-day |
Just to confirm, it was intentional to leave out year-day-month, right?  The reason being: it's not commonly-used

2021-12-23 17:25 UTC, mlipschultz commented on spec.md
> +For every other cell in the possible formats table with multiple formats, only one of the format must satisfy the raw datetime string. If None or more that one format satisfies the datetime string, i
```suggestion
For every other cell in the possible formats table with multiple formats, only one of the formats must satisfy the raw datetime string. If None or more that one format satisfies the datetime string, it is still an ambiguous case.
```

2021-12-23 17:25 UTC, mlipschultz commented on spec.md
> +| 2021/11/07 04:03:00          | None         | None        | 2021-11-07T09:03:00Z          |
Why do the parse results all have `Z`?  I thought that would only show up if the input string had timezone information.

From the example above under Unambiguous Datetime: 
* Raw Datetime: Sunday, May 26th 2013 13:12:12
* `isoformat` result: 2013-05-26T13:12:12|

The result doesn't have a `Z` timezone because it the input doesn't have a timezone (whereas the others in the table do)

2021-12-23 17:25 UTC, mlipschultz commented on task_script_utils/datetime_parser/tz_list.py
> +    "CST",
This isn't a unique abbreviated timezone.  It can be Central Standard Time, Cuba Standard Time, or China Standard Time.

2021-12-23 17:26 UTC, mlipschultz commented
Also, I think the spec looks great!

2021-12-23 18:41 UTC, setiat commented on spec.md
> +- `config (DatetimeConfig, optional)`: You also have an options to pass `DatetimeConfig`. It provides complementary information on how to mark parsed digits as day, month or year and also provide an
fixed.

2021-12-23 18:53 UTC, setiat commented on spec.md
> +![Parse Flow Diagram](./task_script_utils/datetime_parser/parse-white.png)
fixed.

2021-12-23 18:53 UTC, setiat commented on spec.md
> +# Case 2: when raw datetime string doesn't match with one of the format in datetime_formats_list but can be parsed without any ambiguity
fixed

2021-12-23 18:53 UTC, setiat commented on spec.md
> +You can use `SSSSSS` as token to parse any number on digits as fractional seconds.
fixed

2021-12-23 18:53 UTC, setiat commented on spec.md
> +The only way to parse timestamps(if parse-able) is by passing `DatetimeConfig` object with `tz_dict`.
fixed

2021-12-23 18:53 UTC, setiat commented on spec.md
> +`"Z"` can be used as token for capturing abbreviated timezones when using datetime_formats to prase the raw datetime string. Even in this case, for successful parsing, `DatetimeConfig.tz_dict` is req
fixed.

2021-12-23 18:53 UTC, setiat commented on spec.md
> +| May 26th 2013 12:12:12.5677 AM Asia/Kolkata         | 2013-05-26T00:12:12.0001+05:30   |                                                       |
fixed.

2021-12-23 18:54 UTC, setiat commented on spec.md
> +| 21-23-2020T12:13:14                        | Year = 2020, but Can't decide day and month between: ('21', '23')                                 |
fixed.

2021-12-23 18:58 UTC, setiat commented on spec.md
> +| False      | True      | day-month-year                                         |
fixed

2021-12-23 19:05 UTC, setiat commented on spec.md
> +| None       | None      | month-day-year <br> day-month-year <br> year-month-day |
Well, most the matrix remained the same.
What changed is following:
if `year_first` is explicitly  `true` or the format is YYYY-XX-XX, Year-month-day will get precedence over year-day-month.... This  means, for 2012-11-12 , even though it satisfies both YDM and YMD, it is not ambiguous as YMD will be used.

2021-12-23 19:06 UTC, setiat commented on spec.md
> +For every other cell in the possible formats table with multiple formats, only one of the format must satisfy the raw datetime string. If None or more that one format satisfies the datetime string, i
fixed

2021-12-23 19:07 UTC, setiat commented on spec.md
> +| 2021/11/07 04:03:00          | None         | None        | 2021-11-07T09:03:00Z          |
You are right.
I have made the required changes. The code is still good for it. I just messed up the data when formatting it for spec.md

2021-12-23 19:10 UTC, setiat commented on task_script_utils/datetime_parser/tz_list.py
> +    "CST",
- This list of Unique abbreviated TZs  is used for matching the values when parsing using `DatetimeInfo`
- the ambiguity is only resolved if we have an entry for matched value in `DatetimeConfig.tz_dict`

2021-12-23 19:13 UTC, setiat commented on task_script_utils/datetime_parser/tz_list.py
> +    "CST",
This can be improved... we can raise ParserException only for actually ambiguous abbreviations, rest can be mapped from the predefined dict.
But I intentionally left it out, as major objective for today was only to finalise spec.

2022-01-04 23:57 UTC, wkopen requested changes
I really like the spec. Just need to tweak the format a little to make it easier to read and the flow is correct.

2022-01-04 23:57 UTC, wkopen commented on README.md
> +You can read more about the datetime parser [here.](spec.md)
nit: dot should be outside of the bracket.

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +![Parse Flow Diagram](./task_script_utils/datetime_parser/parse-white.png)
1. Why is `spec.md` on the top level? Should it be inside the date time parser source code folder?
2. The flow diagram is great! But if we follow the flow diagram shape meaning strictly the start/end state shape should be a terminator shape not an oval.
3. I think we can make the color the same for function parameters, right now it's blue on the top, but purpose in the diagram. Use a different color for errors
4. The variable names are also different. For example, `DatetimeConfig.fold` in the diagram vs `datetime_config` in the function signature
5. You said fixed but I'm not seeing the diagram updated with what Mike suggested like the start is still in the lower left corner

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +datetime_formats_list = [
insert an empty line above

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +# Case 1: when raw datetime string matches with one of the format in datetime_formats_list
I recommend breaking these cases to different markdown sections so it's easier for people to consume. Less mental overhead. Write comments using text and use code blocks for code.

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +>>> result = parse("21-12-20 12:30:20 Asia/Kolkata", formats_list=datetime_formats_list)
to be honest, these `>>>` are a bit annoying. I suggest putting expected results in comments. Something like:
```
result.tsformat()  # 2020-12-21T07:00:20Z
result.isoformat() # 2020-12-21T12:30:20+05:30
```
It's also easier for users to compare the difference. Easy on the eyes. If you agree, please apply to everywhere in this doc.

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +>>> from task_script_utils.datetime_parser import parse
Same comment on `>>>`

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +- `config: DatetimeConfig (optional)`: You also have an options to pass `DatetimeConfig`. It provides complementary information on how to mark parsed digits as day, month or year and also provide an
I looked at the DatetimeConfig class and found the docstring doesn't have proper indentation. Please correct it.

2022-01-04 23:57 UTC, wkopen commented on README.md
>  from task_script_utils.datetime_parser import convert_to_ts_iso8601
Should be `parse` now right?

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +## Datetime Parser
Renamed to `Usage`

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +`taskscript_utils.datetime_parser` exposes `parse()` method for parsing string datetimes.
put the python code here directly:
`from task_script_utils.datetime_parser import parse`

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +The `parse()` returns a `TSDatetime` object and accepts following arguements:
You can make it more clear by doing

Input:
...

Output:
...

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +| Cases                                      | Reason for ambiguity                                                                              | Note                                           |
Remove spacing in this table

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +## Parsing Fractional Seconds
should this be a sub-section ###?

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +## Parsing Abbreviated Timezones
should this be a sub-section ###?

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +## Parsing Abbreviated Timezones
should this be a sub-section ###?

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +## Unambiguous Datetime
I think this section should be moved up right afer `Usage` section. This is because most times people are "lazy" and just want to see how they can use it without providing any extra config.

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +## Ambiguous Dates
And this section should follow the previous one to be moved up. Once people found their date time is ambiguous, they will have the incentive to define more configs.

2022-01-04 23:57 UTC, wkopen commented on spec.md
> +# TS Datetime Parser
All the sections are on the same level. Let's group them. My suggestion:
```
# TS Datetime Parser
## Usage
## Unambiguous Datetime
## Ambriguous Datetime
### Work with formats_list
### Work with config
## Limitations
```

2022-01-05 03:42 UTC, wkopen requested changes
I left more comments on the integration tests. Please see the comments.

2022-01-05 03:42 UTC, wkopen commented on __tests__/integration/test_parse.py
> +    # Ambiguous / Error Cases
These test cases are not great. They are invalid in the first place. Neither month nor day can be 32. If a value is greater than 12, then automatically the other value is month. However, in cases where a value is greater than 12, the other value is also greater than 12, which makes it invalid. We need to separate ambiguous cases apart from invalid cases

2022-01-05 03:42 UTC, wkopen commented on __tests__/integration/test_parse.py
> +    ("27-12-2002T12:12:12 America/Chicago", None, True, "2002-12-27T12:12:12-06:00"),
The original string is already unambiguous. So another test we should do is, `11-12-2002T12:12:12 America/Chicago` with day_first `True`

2022-01-05 03:42 UTC, wkopen commented on __tests__/integration/test_parse.py
> +    # Note: For short dates with 4 digits year, DatetimeConfig.year_first is ignored
Is this the right behavior? Should we actually throw an error? I'm thinking error is better because the user explicitly set this config however the data shows the other way. It's def not the user's expectation.

2022-01-05 03:42 UTC, wkopen commented on __tests__/integration/test_parse.py
> +    ("11-12-2002T12:12:12 America/Chicago", None, False, "2002-11-12T12:12:12-06:00"),
This is an ambiguous case. The config makes it unambiguous. The ambiguity should be referring to the original string.

2022-01-05 03:42 UTC, wkopen commented on __tests__/integration/test_parse.py
> +    # Unambiguous Cases
Again, I think ambiguity here refers to the original string. Not string + config. So all your test cases here are ambiguous by nature. And that's the point of the tests, we want to show how the config helps with dealing with ambiguity.

2022-01-05 23:44 UTC, wkopen requested changes
Thanks for addressing my comments for spec.md! I assume you haven't finished editing the test cases. I left some comments for the updated content.

2022-01-05 23:44 UTC, wkopen commented on task_script_utils/datetime_parser/spec.md
> +![Parse Flow Diagram](./parse-white.png)
1. In the diagram the `datetime_raw_str` is wrongly named. And `config` is wrongly named.
2. Make `Parse` lowercase

2022-01-05 23:44 UTC, wkopen commented on task_script_utils/datetime_parser/spec.md
> +result.tsformat()   #'2020-12-21T07:00:20Z'
can remove '' now. no longer needed

2022-01-05 23:44 UTC, wkopen commented on task_script_utils/datetime_parser/spec.md
> +| --------------------------------------------------- | -------------------------------- | ----------------------------------------------------- |
Can just be `| - | - | - |`

2022-01-05 23:44 UTC, wkopen commented on task_script_utils/datetime_parser/spec.md
> +| ------ | ---------------------- | ----- |
Can just be | - | - | - |

2022-01-05 23:44 UTC, wkopen commented on task_script_utils/datetime_parser/spec.md
> +| 2021-10-31T02:45:00 Europe/Rome | **AmbiguousFoldError**: DatetimeConfig.fold must not be None to parse datetime without ambiguity. | Can be fixed by passing DatetimeConfig.fold    |
extra spacing for the last item, same for next line

2022-01-05 23:44 UTC, wkopen commented on __tests__/integration/test_parse.py
> +    ("2021-23-13T12:12:12 America/Chicago", None, None, None),
this case is still invalid to start with

2022-01-06 10:28 UTC, setiat commented on __tests__/integration/test_parse.py
> +    # Ambiguous / Error Cases
A question: Test cases are not great in a sense that it doesn't cover the cases...or just that the naming convention in wrong?

If its the naming convention , I have added comments... let me know if they work.
If not I can use suggestion

2022-01-06 11:56 UTC, setiat commented on task_script_utils/datetime_parser/spec.md
> +![Parse Flow Diagram](./parse-white.png)
fixed

2022-01-06 11:56 UTC, setiat commented on task_script_utils/datetime_parser/spec.md
> +result.tsformat()   #'2020-12-21T07:00:20Z'
fixed

2022-01-06 11:56 UTC, setiat commented on task_script_utils/datetime_parser/spec.md
> +| --------------------------------------------------- | -------------------------------- | ----------------------------------------------------- |
fixed

2022-01-06 11:56 UTC, setiat commented on task_script_utils/datetime_parser/spec.md
> +| ------ | ---------------------- | ----- |
fixed

2022-01-06 11:56 UTC, setiat commented on task_script_utils/datetime_parser/spec.md
> +| 2021-10-31T02:45:00 Europe/Rome | **AmbiguousFoldError**: DatetimeConfig.fold must not be None to parse datetime without ambiguity. | Can be fixed by passing DatetimeConfig.fold    |
fixed

2022-01-06 11:57 UTC, setiat commented on __tests__/integration/test_parse.py
> +    ("2021-23-13T12:12:12 America/Chicago", None, None, None),
fixed

2022-01-06 14:23 UTC, wkopen commented on __tests__/integration/test_parse.py
> +    # Ambiguous / Error Cases
@setiat I was referring to "it doesn't cover cases". One idea is to separate Ambiguous cases with Error Cases. Ambiguous cases should still be valid date and time. Error cases, from my understanding that, are invalid date and time (like 32 is impossible for both month and day).

2022-01-13 19:56 UTC, wkopen commented on README.md
> +You can read more about the datetime parser [here.](spec.md)
@tariksetia this is not addressed

2022-01-13 20:11 UTC, wkopen requested changes
Very close! Thank you for addressing most of my comments. Just some very minor changes needed and there is a comment not addressed.

2022-01-13 20:11 UTC, wkopen commented on __tests__/integration/test_parse.py
> +    # Error Cases
To be consistent with how you arranged "four_digit_year_with_no_config_test_cases", can you also divide this into "Invalid Cases" and "Still Ambiguous Cases"?

2022-01-13 20:11 UTC, wkopen commented on task_script_utils/datetime_parser/spec.md
> +# TS Datetime Parser
Nice! This file can be renamed to README.md now.

2022-01-13 20:11 UTC, wkopen commented on task_script_utils/datetime_parser/spec.md
> +   eg.`parse('2021-12-08')` or `parse('12:00:00')` will raise `InvalidDateError`
e.g. with a space after

2022-01-17 12:11 UTC, setiat commented on spec.md
> +- `config: DatetimeConfig (optional)`: You also have an options to pass `DatetimeConfig`. It provides complementary information on how to mark parsed digits as day, month or year and also provide an
I used the auto generated docstrings with default indentation. Could you please help me pin point the issue... Meanwhile, I have made changes to make it more readable.

Also I think, Usage section should be kept simple and as is. Because if I move the corollary case here, user must first know about DatetimeConfig class and how it works.

As a solution, I can provide a link here, navigation to Datetime Config section.
Thoughts?

2022-01-17 12:11 UTC, setiat commented on spec.md
> +## Datetime Parser
renamed

2022-01-17 12:11 UTC, setiat commented on __tests__/integration/test_parse.py
> +    # Error Cases
fixed

2022-01-17 12:17 UTC, setiat commented
@wkopen Here is the link to to how datetime format resolution works for 2 digits date: https://github.com/tetrascience/ts-task-script-utils/blob/DE-2591-refactor/task_script_utils/datetime_parser/short-date-format-resolution.png

If it looks ok, I can add it to the documentation

2022-01-17 14:00 UTC, setiat commented on README.md
> +You can read more about the datetime parser [here.](spec.md)
I truncated the readme. It now contains mini intro to date_time parser with link to spec/readme.md

2022-01-17 14:01 UTC, setiat commented on README.md
> +You can read more about the datetime parser [here.](spec.md)
Should I Merge the spec with README.md?

2022-01-24 03:17 UTC, wkopen commented
There are some code logic change in https://github.com/tetrascience/ts-task-script-utils/pull/8/commits/bfc5457322f3342f40b5fa8c1ade1a92052360b3 besides the suggested changes I commented. @mlipschultz can you check it?

2022-01-24 18:20 UTC, mlipschultz commented
The logic looks good to me.  I actually like it more than `_process_day_and_month`.  While reviewing this, I found a couple minor issues with `_try_formats`, but since they were outside the scope of this PR, I left them in the main PR.  They don't affect functionality, it's just a small typo in a docstring and an inaccurate type hint.

Also, @wkopen, do you have an opinion on [Tarik's question](https://github.com/tetrascience/ts-task-script-utils/pull/8#discussion_r786031121):
> Should I Merge the spec with README.md?

2022-01-25 13:31 UTC, wkopen commented on README.md
> +You can read more about the datetime parser [here.](spec.md)
It should be "You can read more about the datetime parser [here](task_script_utils/datetime_parser/README.md)." with the period not in []

2022-01-25 13:34 UTC, setiat commented on spec.md
> +- `config: DatetimeConfig (optional)`: You also have an options to pass `DatetimeConfig`. It provides complementary information on how to mark parsed digits as day, month or year and also provide an
@wkopen ...this one

2022-01-25 14:01 UTC, wkopen approved these changes
Ready to ship!

2022-01-26 05:23 UTC, merged